const files = [
  'ADT.png',
  'AMD.png',
  'Adidas.png',
  'Airbnb.png',
  'Amazon.png',
  'Anker.png',
  'Apple.png',
  'Asos.png',
  'Atari.png',
  'BMW.png',
  'BP.png',
  'Balenciaga.png',
  'BandMBargains.png',
  'BandaiNamco.png',
  'BankOfAmerica.png',
  'Barclays.png',
  'Bing.png',
  'Bitcoin.png',
  'Booking.png',
  'CNBC.png',
  'Capcom.png',
  'Champion.png',
  'Cisco.png',
  'Citroen.png',
  'Coke.png',
  'Costa.png',
  'Crunchyroll.png',
  'Dodge.png',
  'Dolby.png',
  'Dominos.png',
  'DreamWorks.png',
  'Ducati.png',
  'Ebay.png',
  'Eizo.png',
  'Ericsson.png',
  'Facebook.png',
  'Fjallraven.png',
  'Ford.png',
  'Github.png',
  'Givenchy.png',
  'Google.png',
  'Goyard.png',
  'Gucci.png',
  'Honda.png',
  'Huawei.png',
  'IBM.png',
  'Infiniti.png',
  'Intel.png',
  'Jaguar.png',
  'JohnDeere.png',
  'KFC.png',
  'Kappa.png',
  'Koenigsegg.png',
  'LG.png',
  'Lamborghini.png',
  'Lexus.png',
  'Liteon.png',
  'LouisVuitton.png',
  'MTV.png',
  'Maersk.png',
  'Mazda.png',
  'McDonalds.png',
  'MercedesBenz.png',
  'Microsoft.png',
  'Mitsubishi.png',
  'Monster.png',
  'MonsterCable.png',
  'Nandos.png',
  'Napster.png',
  'Nestle.png',
  'Netflix.png',
  'Nike.png',
  'Nintendo.png',
  'Novation.png',
  'Nvidia.png',
  'PapaJohns.png',
  'Patagonia.png',
  'Peugeot.png',
  'Philips.png',
  'Pioneer.png',
  'PizzaHut.png',
  'Playboy.png',
  'Playstation.png',
  'Porsche.png',
  'Rayban.png',
  'Razer.png',
  'RedBull.png',
  'RioTinto.png',
  'Rossignol.png',
  'SAP.png',
  'Samsung.png',
  'Sanyo.png',
  'Shell.png',
  'Skullcandy.png',
  'Skype.png',
  'Snapchat.png',
  'Sonos.png',
  'Sony.png',
  'Soundcloud.png',
  'Spotify.png',
  'Starbucks.png',
  'Steam.png',
  'Subway.png',
  'Superdry.png',
  'Supreme.png',
  'Tannoy.png',
  'Tesla.png',
  'TheHundreds.png',
  'Timberland.png',
  'Toyota.png',
  'Twitch.png',
  'Twitter.png',
  'Uber.png',
  'Ubisoft.png',
  'Vine.png',
  'Visa.png',
  'Volkswagen.png',
  'Wikipedia.png',
  'Xbox.png',
  'YSL.png',
  'Yamaha.png',
];

export function generate() {
  const result = files.map((file, index) => {
    const nameWithoutExtension = file.replace('.png', '');

    return {
      id: index + 1,
      answers: [
        {
          value: nameWithoutExtension,
        },
      ],
      question: `logo/${file}`,
      hints: [
        {
          id: '0',
          label: 'Odsłoń pierwsze fragmenty logo',
          content: '3',
          penaltyPercent: 0,
        },
        {
          id: '1',
          label: 'Odsłoń kolejne fragmenty logo',
          content: '5',
          penaltyPercent: 20,
        },
        {
          id: '2',
          label: 'Odsłoń kolejne fragmenty logo',
          content: '10',
          penaltyPercent: 20,
        },
      ],
      revealedAnswers: [],
    };
  });

  console.log(JSON.stringify(result, null, 2));
}
