export const ODLEGLOSCI_MIASTOWE = [
  {
    id: 1,
    answers: [{ label: 'odległość', value: '300 km' }],
    question: 'WARSZAWA -> KRAKÓW',
    hints: [{ id: '1-0', label: 'WARSZAWA -> KRAKÓW', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 2,
    answers: [{ label: 'odległość', value: '140 km' }],
    question: 'WARSZAWA -> ŁÓDŹ',
    hints: [{ id: '2-0', label: 'WARSZAWA -> ŁÓDŹ', content: 'Można się pomylić o 10 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 3,
    answers: [{ label: 'odległość', value: '310 km' }],
    question: 'WARSZAWA -> WROCŁAW',
    hints: [{ id: '3-0', label: 'WARSZAWA -> WROCŁAW', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 4,
    answers: [{ label: 'odległość', value: '310 km' }],
    question: 'WARSZAWA -> POZNAŃ',
    hints: [{ id: '4-0', label: 'WARSZAWA -> POZNAŃ', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 5,
    answers: [{ label: 'odległość', value: '340 km' }],
    question: 'WARSZAWA -> GDAŃSK',
    hints: [{ id: '5-0', label: 'WARSZAWA -> GDAŃSK', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 6,
    answers: [{ label: 'odległość', value: '570 km' }],
    question: 'WARSZAWA -> SZCZECIN',
    hints: [{ id: '6-0', label: 'WARSZAWA -> SZCZECIN', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 7,
    answers: [{ label: 'odległość', value: '230 km' }],
    question: 'WARSZAWA -> BYDGOSZCZ',
    hints: [{ id: '7-0', label: 'WARSZAWA -> BYDGOSZCZ', content: 'Można się pomylić o 18 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 8,
    answers: [{ label: 'odległość', value: '190 km' }],
    question: 'WARSZAWA -> LUBLIN',
    hints: [{ id: '8-0', label: 'WARSZAWA -> LUBLIN', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 9,
    answers: [{ label: 'odległość', value: '200 km' }],
    question: 'WARSZAWA -> BIAŁYSTOK',
    hints: [{ id: '9-0', label: 'WARSZAWA -> BIAŁYSTOK', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 10,
    answers: [{ label: 'odległość', value: '260 km' }],
    question: 'WARSZAWA -> KATOWICE',
    hints: [{ id: '10-0', label: 'WARSZAWA -> KATOWICE', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 11,
    answers: [{ label: 'odległość', value: '350 km' }],
    question: 'WARSZAWA -> GDYNIA',
    hints: [{ id: '11-0', label: 'WARSZAWA -> GDYNIA', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 12,
    answers: [{ label: 'odległość', value: '210 km' }],
    question: 'WARSZAWA -> CZĘSTOCHOWA',
    hints: [{ id: '12-0', label: 'WARSZAWA -> CZĘSTOCHOWA', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 13,
    answers: [{ label: 'odległość', value: '100 km' }],
    question: 'WARSZAWA -> RADOM',
    hints: [{ id: '13-0', label: 'WARSZAWA -> RADOM', content: 'Można się pomylić o 8 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 14,
    answers: [{ label: 'odległość', value: '270 km' }],
    question: 'WARSZAWA -> SOSNOWIEC',
    hints: [{ id: '14-0', label: 'WARSZAWA -> SOSNOWIEC', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 15,
    answers: [{ label: 'odległość', value: '210 km' }],
    question: 'WARSZAWA -> TORUŃ',
    hints: [{ id: '15-0', label: 'WARSZAWA -> TORUŃ', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 16,
    answers: [{ label: 'odległość', value: '180 km' }],
    question: 'WARSZAWA -> KIELCE',
    hints: [{ id: '16-0', label: 'WARSZAWA -> KIELCE', content: 'Można się pomylić o 14 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 17,
    answers: [{ label: 'odległość', value: '290 km' }],
    question: 'WARSZAWA -> RZESZÓW',
    hints: [{ id: '17-0', label: 'WARSZAWA -> RZESZÓW', content: 'Można się pomylić o 22 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 18,
    answers: [{ label: 'odległość', value: '290 km' }],
    question: 'WARSZAWA -> GLIWICE',
    hints: [{ id: '18-0', label: 'WARSZAWA -> GLIWICE', content: 'Można się pomylić o 22 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 19,
    answers: [{ label: 'odległość', value: '300 km' }],
    question: 'WARSZAWA -> ZABRZE',
    hints: [{ id: '19-0', label: 'WARSZAWA -> ZABRZE', content: 'Można się pomylić o 22 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 20,
    answers: [{ label: 'odległość', value: '110 km' }],
    question: 'WARSZAWA -> PŁOCK',
    hints: [{ id: '20-0', label: 'WARSZAWA -> PŁOCK', content: 'Można się pomylić o 8 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 21,
    answers: [{ label: 'odległość', value: '210 km' }],
    question: 'WARSZAWA -> OLSZTYN',
    hints: [{ id: '21-0', label: 'WARSZAWA -> OLSZTYN', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 22,
    answers: [{ label: 'odległość', value: '330 km' }],
    question: 'WARSZAWA -> BIELSKO-BIAŁA',
    hints: [{ id: '22-0', label: 'WARSZAWA -> BIELSKO-BIAŁA', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 23,
    answers: [{ label: 'odległość', value: '280 km' }],
    question: 'WARSZAWA -> BYTOM',
    hints: [{ id: '23-0', label: 'WARSZAWA -> BYTOM', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 24,
    answers: [{ label: 'odległość', value: '450 km' }],
    question: 'WARSZAWA -> ZIELONA GÓRA',
    hints: [{ id: '24-0', label: 'WARSZAWA -> ZIELONA GÓRA', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 25,
    answers: [{ label: 'odległość', value: '270 km' }],
    question: 'WARSZAWA -> CHORZÓW',
    hints: [{ id: '25-0', label: 'WARSZAWA -> CHORZÓW', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 26,
    answers: [{ label: 'odległość', value: '430 km' }],
    question: 'WARSZAWA -> LEGNICA',
    hints: [{ id: '26-0', label: 'WARSZAWA -> LEGNICA', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 27,
    answers: [{ label: 'odległość', value: '230 km' }],
    question: 'WARSZAWA -> KALISZ',
    hints: [{ id: '27-0', label: 'WARSZAWA -> KALISZ', content: 'Można się pomylić o 18 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 28,
    answers: [{ label: 'odległość', value: '460 km' }],
    question: 'WARSZAWA -> GORZÓW WIELKOPOLSKI',
    hints: [{ id: '28-0', label: 'WARSZAWA -> GORZÓW WIELKOPOLSKI', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 29,
    answers: [{ label: 'odległość', value: '500 km' }],
    question: 'WARSZAWA -> KOSZALIN',
    hints: [{ id: '29-0', label: 'WARSZAWA -> KOSZALIN', content: 'Można się pomylić o 38 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 30,
    answers: [{ label: 'odległość', value: '280 km' }],
    question: 'WARSZAWA -> TARNÓW',
    hints: [{ id: '30-0', label: 'WARSZAWA -> TARNÓW', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 31,
    answers: [{ label: 'odległość', value: '440 km' }],
    question: 'WARSZAWA -> LUBIN',
    hints: [{ id: '31-0', label: 'WARSZAWA -> LUBIN', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 32,
    answers: [{ label: 'odległość', value: '310 km' }],
    question: 'WARSZAWA -> OPOLE',
    hints: [{ id: '32-0', label: 'WARSZAWA -> OPOLE', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 33,
    answers: [{ label: 'odległość', value: '160 km' }],
    question: 'WARSZAWA -> WŁOCŁAWEK',
    hints: [{ id: '33-0', label: 'WARSZAWA -> WŁOCŁAWEK', content: 'Można się pomylić o 12 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 34,
    answers: [{ label: 'odległość', value: '95 km' }],
    question: 'WARSZAWA -> SIEDLCE',
    hints: [{ id: '34-0', label: 'WARSZAWA -> SIEDLCE', content: 'Można się pomylić o 7 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 35,
    answers: [{ label: 'odległość', value: '360 km' }],
    question: 'WARSZAWA -> JASTRZĘBIE-ZDRÓJ',
    hints: [{ id: '35-0', label: 'WARSZAWA -> JASTRZĘBIE-ZDRÓJ', content: 'Można się pomylić o 28 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 36,
    answers: [{ label: 'odległość', value: '320 km' }],
    question: 'WARSZAWA -> NIEPOŁOMICE',
    hints: [{ id: '36-0', label: 'WARSZAWA -> NIEPOŁOMICE', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 37,
    answers: [{ label: 'odległość', value: '250 km' }],
    question: 'WARSZAWA -> MIELEC',
    hints: [{ id: '37-0', label: 'WARSZAWA -> MIELEC', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 38,
    answers: [{ label: 'odległość', value: '160 km' }],
    question: 'WARSZAWA -> BEŁCHATÓW',
    hints: [{ id: '38-0', label: 'WARSZAWA -> BEŁCHATÓW', content: 'Można się pomylić o 12 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 39,
    answers: [{ label: 'odległość', value: '620 km' }],
    question: 'WARSZAWA -> ŚWINOUJŚCIE',
    hints: [{ id: '39-0', label: 'WARSZAWA -> ŚWINOUJŚCIE', content: 'Można się pomylić o 45 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 40,
    answers: [{ label: 'odległość', value: '480 km' }],
    question: 'WARSZAWA -> KOŁOBRZEG',
    hints: [{ id: '40-0', label: 'WARSZAWA -> KOŁOBRZEG', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 41,
    answers: [{ label: 'odległość', value: '250 km' }],
    question: 'GLIWICE -> PŁOCK',
    hints: [{ id: '41-0', label: 'GLIWICE -> PŁOCK', content: 'Można się pomylić o 18 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 42,
    answers: [{ label: 'odległość', value: '520 km' }],
    question: 'GLIWICE -> SZCZECIN',
    hints: [{ id: '42-0', label: 'GLIWICE -> SZCZECIN', content: 'Można się pomylić o 38 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 43,
    answers: [{ label: 'odległość', value: '20 km' }],
    question: 'KATOWICE -> ZABRZE',
    hints: [{ id: '43-0', label: 'KATOWICE -> ZABRZE', content: 'Można się pomylić o 2 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 44,
    answers: [{ label: 'odległość', value: '600 km' }],
    question: 'GDAŃSK -> KRAKÓW',
    hints: [{ id: '44-0', label: 'GDAŃSK -> KRAKÓW', content: 'Można się pomylić o 45 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 45,
    answers: [{ label: 'odległość', value: '480 km' }],
    question: 'WROCŁAW -> GDAŃSK',
    hints: [{ id: '45-0', label: 'WROCŁAW -> GDAŃSK', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 46,
    answers: [{ label: 'odległość', value: '180 km' }],
    question: 'POZNAŃ -> WROCŁAW',
    hints: [{ id: '46-0', label: 'POZNAŃ -> WROCŁAW', content: 'Można się pomylić o 14 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 47,
    answers: [{ label: 'odległość', value: '330 km' }],
    question: 'LUBLIN -> KRAKÓW',
    hints: [{ id: '47-0', label: 'LUBLIN -> KRAKÓW', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 48,
    answers: [{ label: 'odległość', value: '540 km' }],
    question: 'BIAŁYSTOK -> WROCŁAW',
    hints: [{ id: '48-0', label: 'BIAŁYSTOK -> WROCŁAW', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 49,
    answers: [{ label: 'odległość', value: '160 km' }],
    question: 'BYDGOSZCZ -> POZNAŃ',
    hints: [{ id: '49-0', label: 'BYDGOSZCZ -> POZNAŃ', content: 'Można się pomylić o 12 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 50,
    answers: [{ label: 'odległość', value: '210 km' }],
    question: 'RZESZÓW -> LUBLIN',
    hints: [{ id: '50-0', label: 'RZESZÓW -> LUBLIN', content: 'Można się pomylić o 16 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 51,
    answers: [{ label: 'odległość', value: '45 km' }],
    question: 'GDAŃSK -> GDYNIA',
    hints: [{ id: '51-0', label: 'GDAŃSK -> GDYNIA', content: 'Można się pomylić o 3 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 52,
    answers: [{ label: 'odległość', value: '130 km' }],
    question: 'CZĘSTOCHOWA -> KATOWICE',
    hints: [{ id: '52-0', label: 'CZĘSTOCHOWA -> KATOWICE', content: 'Można się pomylić o 10 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 53,
    answers: [{ label: 'odległość', value: '260 km' }],
    question: 'SZCZECIN -> POZNAŃ',
    hints: [{ id: '53-0', label: 'SZCZECIN -> POZNAŃ', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 54,
    answers: [{ label: 'odległość', value: '380 km' }],
    question: 'OLSZTYN -> WARSZAWA',
    hints: [{ id: '54-0', label: 'OLSZTYN -> WARSZAWA', content: 'Można się pomylić o 28 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 55,
    answers: [{ label: 'odległość', value: '120 km' }],
    question: 'KIELCE -> RADOM',
    hints: [{ id: '55-0', label: 'KIELCE -> RADOM', content: 'Można się pomylić o 9 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 56,
    answers: [{ label: 'odległość', value: '430 km' }],
    question: 'BIAŁYSTOK -> GDAŃSK',
    hints: [{ id: '56-0', label: 'BIAŁYSTOK -> GDAŃSK', content: 'Można się pomylić o 32 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 57,
    answers: [{ label: 'odległość', value: '170 km' }],
    question: 'ŁÓDŹ -> WROCŁAW',
    hints: [{ id: '57-0', label: 'ŁÓDŹ -> WROCŁAW', content: 'Można się pomylić o 13 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 58,
    answers: [{ label: 'odległość', value: '350 km' }],
    question: 'ZIELONA GÓRA -> POZNAŃ',
    hints: [{ id: '58-0', label: 'ZIELONA GÓRA -> POZNAŃ', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 59,
    answers: [{ label: 'odległość', value: '100 km' }],
    question: 'TORUŃ -> BYDGOSZCZ',
    hints: [{ id: '59-0', label: 'TORUŃ -> BYDGOSZCZ', content: 'Można się pomylić o 8 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 60,
    answers: [{ label: 'odległość', value: '550 km' }],
    question: 'RZESZÓW -> SZCZECIN',
    hints: [{ id: '60-0', label: 'RZESZÓW -> SZCZECIN', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 61,
    answers: [{ label: 'odległość', value: '190 km' }],
    question: 'LUBLIN -> WARSZAWA',
    hints: [{ id: '61-0', label: 'LUBLIN -> WARSZAWA', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 62,
    answers: [{ label: 'odległość', value: '280 km' }],
    question: 'WROCŁAW -> KATOWICE',
    hints: [{ id: '62-0', label: 'WROCŁAW -> KATOWICE', content: 'Można się pomylić o 22 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 63,
    answers: [{ label: 'odległość', value: '150 km' }],
    question: 'BIELSKO-BIAŁA -> KRAKÓW',
    hints: [{ id: '63-0', label: 'BIELSKO-BIAŁA -> KRAKÓW', content: 'Można się pomylić o 11 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 64,
    answers: [{ label: 'odległość', value: '390 km' }],
    question: 'CZĘSTOCHOWA -> GDAŃSK',
    hints: [{ id: '64-0', label: 'CZĘSTOCHOWA -> GDAŃSK', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 65,
    answers: [{ label: 'odległość', value: '210 km' }],
    question: 'PŁOCK -> ŁÓDŹ',
    hints: [{ id: '65-0', label: 'PŁOCK -> ŁÓDŹ', content: 'Można się pomylić o 16 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 66,
    answers: [{ label: 'odległość', value: '90 km' }],
    question: 'LEGNICA -> WROCŁAW',
    hints: [{ id: '66-0', label: 'LEGNICA -> WROCŁAW', content: 'Można się pomylić o 7 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 67,
    answers: [{ label: 'odległość', value: '320 km' }],
    question: 'OPOLE -> WARSZAWA',
    hints: [{ id: '67-0', label: 'OPOLE -> WARSZAWA', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 68,
    answers: [{ label: 'odległość', value: '500 km' }],
    question: 'SUWAŁKI -> WROCŁAW',
    hints: [{ id: '68-0', label: 'SUWAŁKI -> WROCŁAW', content: 'Można się pomylić o 38 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 69,
    answers: [{ label: 'odległość', value: '160 km' }],
    question: 'TARNOW -> KRAKOW',
    hints: [{ id: '69-0', label: 'TARNOW -> KRAKOW', content: 'Można się pomylić o 12 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 70,
    answers: [{ label: 'odległość', value: '440 km' }],
    question: 'GORZÓW WIELKOPOLSKI -> WARSZAWA',
    hints: [{ id: '70-0', label: 'GORZÓW WIELKOPOLSKI -> WARSZAWA', content: 'Można się pomylić o 33 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 71,
    answers: [{ label: 'odległość', value: '430 km' }],
    question: 'BIAŁYSTOK -> KRAKÓW',
    hints: [{ id: '71-0', label: 'BIAŁYSTOK -> KRAKÓW', content: 'Można się pomylić o 32 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 72,
    answers: [{ label: 'odległość', value: '230 km' }],
    question: 'RZESZÓW -> KATOWICE',
    hints: [{ id: '72-0', label: 'RZESZÓW -> KATOWICE', content: 'Można się pomylić o 18 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 73,
    answers: [{ label: 'odległość', value: '380 km' }],
    question: 'CZĘSTOCHOWA -> POZNAŃ',
    hints: [{ id: '73-0', label: 'CZĘSTOCHOWA -> POZNAŃ', content: 'Można się pomylić o 28 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 74,
    answers: [{ label: 'odległość', value: '110 km' }],
    question: 'BYDGOSZCZ -> GDAŃSK',
    hints: [{ id: '74-0', label: 'BYDGOSZCZ -> GDAŃSK', content: 'Można się pomylić o 8 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 75,
    answers: [{ label: 'odległość', value: '260 km' }],
    question: 'WŁOCŁAWEK -> WROCŁAW',
    hints: [{ id: '75-0', label: 'WŁOCŁAWEK -> WROCŁAW', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 76,
    answers: [{ label: 'odległość', value: '460 km' }],
    question: 'LUBLIN -> GDAŃSK',
    hints: [{ id: '76-0', label: 'LUBLIN -> GDAŃSK', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 77,
    answers: [{ label: 'odległość', value: '55 km' }],
    question: 'SOSNOWIEC -> GLIWICE',
    hints: [{ id: '77-0', label: 'SOSNOWIEC -> GLIWICE', content: 'Można się pomylić o 4 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 78,
    answers: [{ label: 'odległość', value: '350 km' }],
    question: 'SZCZECIN -> WROCŁAW',
    hints: [{ id: '78-0', label: 'SZCZECIN -> WROCŁAW', content: 'Można się pomylić o 26 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 79,
    answers: [{ label: 'odległość', value: '190 km' }],
    question: 'SIEDLCE -> LUBLIN',
    hints: [{ id: '79-0', label: 'SIEDLCE -> LUBLIN', content: 'Można się pomylić o 14 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 80,
    answers: [{ label: 'odległość', value: '290 km' }],
    question: 'OLSZTYN -> GDAŃSK',
    hints: [{ id: '80-0', label: 'OLSZTYN -> GDAŃSK', content: 'Można się pomylić o 22 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 81,
    answers: [{ label: 'odległość', value: '310 km' }],
    question: 'KIELCE -> ŁÓDŹ',
    hints: [{ id: '81-0', label: 'KIELCE -> ŁÓDŹ', content: 'Można się pomylić o 23 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 82,
    answers: [{ label: 'odległość', value: '240 km' }],
    question: 'RADOM -> KRAKÓW',
    hints: [{ id: '82-0', label: 'RADOM -> KRAKÓW', content: 'Można się pomylić o 18 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 83,
    answers: [{ label: 'odległość', value: '420 km' }],
    question: 'ZIELONA GÓRA -> GDAŃSK',
    hints: [{ id: '83-0', label: 'ZIELONA GÓRA -> GDAŃSK', content: 'Można się pomylić o 32 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 84,
    answers: [{ label: 'odległość', value: '130 km' }],
    question: 'OPOLE -> WROCŁAW',
    hints: [{ id: '84-0', label: 'OPOLE -> WROCŁAW', content: 'Można się pomylić o 10 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 85,
    answers: [{ label: 'odległość', value: '590 km' }],
    question: 'RZESZÓW -> GDAŃSK',
    hints: [{ id: '85-0', label: 'RZESZÓW -> GDAŃSK', content: 'Można się pomylić o 45 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 86,
    answers: [{ label: 'odległość', value: '70 km' }],
    question: 'TARNOW -> RZESZOW',
    hints: [{ id: '86-0', label: 'TARNOW -> RZESZOW', content: 'Można się pomylić o 5 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 87,
    answers: [{ label: 'odległość', value: '250 km' }],
    question: 'KALISZ -> WARSZAWA',
    hints: [{ id: '87-0', label: 'KALISZ -> WARSZAWA', content: 'Można się pomylić o 19 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 88,
    answers: [{ label: 'odległość', value: '180 km' }],
    question: 'GORZÓW WIELKOPOLSKI -> POZNAŃ',
    hints: [{ id: '88-0', label: 'GORZÓW WIELKOPOLSKI -> POZNAŃ', content: 'Można się pomylić o 14 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 89,
    answers: [{ label: 'odległość', value: '410 km' }],
    question: 'KOSZALIN -> POZNAŃ',
    hints: [{ id: '89-0', label: 'KOSZALIN -> POZNAŃ', content: 'Można się pomylić o 31 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 90,
    answers: [{ label: 'odległość', value: '105 km' }],
    question: 'PŁOCK -> TORUŃ',
    hints: [{ id: '90-0', label: 'PŁOCK -> TORUŃ', content: 'Można się pomylić o 8 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 91,
    answers: [{ label: 'odległość', value: '340 km' }],
    question: 'BEŁCHATÓW -> GDAŃSK',
    hints: [{ id: '91-0', label: 'BEŁCHATÓW -> GDAŃSK', content: 'Można się pomylić o 26 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 92,
    answers: [{ label: 'odległość', value: '190 km' }],
    question: 'ELBLĄG -> WARSZAWA',
    hints: [{ id: '92-0', label: 'ELBLĄG -> WARSZAWA', content: 'Można się pomylić o 14 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 93,
    answers: [{ label: 'odległość', value: '280 km' }],
    question: 'WAŁBRZYCH -> ŁÓDŹ',
    hints: [{ id: '93-0', label: 'WAŁBRZYCH -> ŁÓDŹ', content: 'Można się pomylić o 21 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 94,
    answers: [{ label: 'odległość', value: '150 km' }],
    question: 'GRUDZIĄDZ -> POZNAŃ',
    hints: [{ id: '94-0', label: 'GRUDZIĄDZ -> POZNAŃ', content: 'Można się pomylić o 11 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 95,
    answers: [{ label: 'odległość', value: '490 km' }],
    question: 'PRZEMYŚL -> WARSZAWA',
    hints: [{ id: '95-0', label: 'PRZEMYŚL -> WARSZAWA', content: 'Można się pomylić o 37 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 96,
    answers: [{ label: 'odległość', value: '210 km' }],
    question: 'SŁUPSK -> GDAŃSK',
    hints: [{ id: '96-0', label: 'SŁUPSK -> GDAŃSK', content: 'Można się pomylić o 16 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 97,
    answers: [{ label: 'odległość', value: '145 km' }],
    question: 'LEGNICA -> ZIELONA GÓRA',
    hints: [{ id: '97-0', label: 'LEGNICA -> ZIELONA GÓRA', content: 'Można się pomylić o 11 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 98,
    answers: [{ label: 'odległość', value: '300 km' }],
    question: 'JASTRZĘBIE-ZDRÓJ -> WROCŁAW',
    hints: [{ id: '98-0', label: 'JASTRZĘBIE-ZDRÓJ -> WROCŁAW', content: 'Można się pomylić o 23 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 99,
    answers: [{ label: 'odległość', value: '470 km' }],
    question: 'KOŁOBRZEG -> WROCŁAW',
    hints: [{ id: '99-0', label: 'KOŁOBRZEG -> WROCŁAW', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 100,
    answers: [{ label: 'odległość', value: '18 km' }],
    question: 'BYTOM -> CHORZÓW',
    hints: [{ id: '100-0', label: 'BYTOM -> CHORZÓW', content: 'Można się pomylić o 1 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 101,
    answers: [{ label: 'odległość', value: '570 km' }],
    question: 'WARSZAWA -> BERLIN',
    hints: [{ id: '101-0', label: 'WARSZAWA -> BERLIN', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 102,
    answers: [{ label: 'odległość', value: '680 km' }],
    question: 'WARSZAWA -> WIEDEŃ',
    hints: [{ id: '102-0', label: 'WARSZAWA -> WIEDEŃ', content: 'Można się pomylić o 45 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 103,
    answers: [{ label: 'odległość', value: '670 km' }],
    question: 'GLIWICE -> WIEDEŃ',
    hints: [{ id: '103-0', label: 'GLIWICE -> WIEDEŃ', content: 'Można się pomylić o 45 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 104,
    answers: [{ label: 'odległość', value: '1600 km' }],
    question: 'WARSZAWA -> PARYŻ',
    hints: [{ id: '104-0', label: 'WARSZAWA -> PARYŻ', content: 'Można się pomylić o 110 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 105,
    answers: [{ label: 'odległość', value: '1800 km' }],
    question: 'WARSZAWA -> RZYM',
    hints: [{ id: '105-0', label: 'WARSZAWA -> RZYM', content: 'Można się pomylić o 120 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 106,
    answers: [{ label: 'odległość', value: '1350 km' }],
    question: 'GLIWICE -> RZYM',
    hints: [{ id: '106-0', label: 'GLIWICE -> RZYM', content: 'Można się pomylić o 95 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 107,
    answers: [{ label: 'odległość', value: '1100 km' }],
    question: 'WARSZAWA -> AMSTERDAM',
    hints: [{ id: '107-0', label: 'WARSZAWA -> AMSTERDAM', content: 'Można się pomylić o 75 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 108,
    answers: [{ label: 'odległość', value: '2850 km' }],
    question: 'WARSZAWA -> MADRYT',
    hints: [{ id: '108-0', label: 'WARSZAWA -> MADRYT', content: 'Można się pomylić o 190 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 109,
    answers: [{ label: 'odległość', value: '2550 km' }],
    question: 'GLIWICE -> MADRYT',
    hints: [{ id: '109-0', label: 'GLIWICE -> MADRYT', content: 'Można się pomylić o 170 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 110,
    answers: [{ label: 'odległość', value: '450 km' }],
    question: 'WARSZAWA -> WILNO',
    hints: [{ id: '110-0', label: 'WARSZAWA -> WILNO', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 111,
    answers: [{ label: 'odległość', value: '670 km' }],
    question: 'WARSZAWA -> PRAGA',
    hints: [{ id: '111-0', label: 'WARSZAWA -> PRAGA', content: 'Można się pomylić o 45 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 112,
    answers: [{ label: 'odległość', value: '280 km' }],
    question: 'GLIWICE -> PRAGA',
    hints: [{ id: '112-0', label: 'GLIWICE -> PRAGA', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 113,
    answers: [{ label: 'odległość', value: '850 km' }],
    question: 'WARSZAWA -> HAMBURG',
    hints: [{ id: '113-0', label: 'WARSZAWA -> HAMBURG', content: 'Można się pomylić o 60 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 114,
    answers: [{ label: 'odległość', value: '1150 km' }],
    question: 'WARSZAWA -> MONACHIUM',
    hints: [{ id: '114-0', label: 'WARSZAWA -> MONACHIUM', content: 'Można się pomylić o 80 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 115,
    answers: [{ label: 'odległość', value: '800 km' }],
    question: 'GLIWICE -> MONACHIUM',
    hints: [{ id: '115-0', label: 'GLIWICE -> MONACHIUM', content: 'Można się pomylić o 55 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 116,
    answers: [{ label: 'odległość', value: '950 km' }],
    question: 'WARSZAWA -> KOPENHAGA',
    hints: [{ id: '116-0', label: 'WARSZAWA -> KOPENHAGA', content: 'Można się pomylić o 65 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 117,
    answers: [{ label: 'odległość', value: '1650 km' }],
    question: 'WARSZAWA -> LONDYN',
    hints: [{ id: '117-0', label: 'WARSZAWA -> LONDYN', content: 'Można się pomylić o 115 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 118,
    answers: [{ label: 'odległość', value: '3150 km' }],
    question: 'WARSZAWA -> LIZBONA',
    hints: [{ id: '118-0', label: 'WARSZAWA -> LIZBONA', content: 'Można się pomylić o 210 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 119,
    answers: [{ label: 'odległość', value: '1250 km' }],
    question: 'GLIWICE -> BARCELONA',
    hints: [{ id: '119-0', label: 'GLIWICE -> BARCELONA', content: 'Można się pomylić o 85 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 120,
    answers: [{ label: 'odległość', value: '1300 km' }],
    question: 'WARSZAWA -> BRUKSELA',
    hints: [{ id: '120-0', label: 'WARSZAWA -> BRUKSELA', content: 'Można się pomylić o 90 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 121,
    answers: [{ label: 'odległość', value: '940 km' }],
    question: 'WARSZAWA -> RYGA',
    hints: [{ id: '121-0', label: 'WARSZAWA -> RYGA', content: 'Można się pomylić o 60 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 122,
    answers: [{ label: 'odległość', value: '1250 km' }],
    question: 'WARSZAWA -> TALLINN',
    hints: [{ id: '122-0', label: 'WARSZAWA -> TALLINN', content: 'Można się pomylić o 85 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 123,
    answers: [{ label: 'odległość', value: '1180 km' }],
    question: 'WARSZAWA -> SZTOKHOLM',
    hints: [{ id: '123-0', label: 'WARSZAWA -> SZTOKHOLM', content: 'Można się pomylić o 80 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 124,
    answers: [{ label: 'odległość', value: '1550 km' }],
    question: 'GLIWICE -> MEDIOLAN',
    hints: [{ id: '124-0', label: 'GLIWICE -> MEDIOLAN', content: 'Można się pomylić o 105 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 125,
    answers: [{ label: 'odległość', value: '1200 km' }],
    question: 'WARSZAWA -> ZURYCH',
    hints: [{ id: '125-0', label: 'WARSZAWA -> ZURYCH', content: 'Można się pomylić o 80 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 126,
    answers: [{ label: 'odległość', value: '750 km' }],
    question: 'GLIWICE -> BUDAPESZT',
    hints: [{ id: '126-0', label: 'GLIWICE -> BUDAPESZT', content: 'Można się pomylić o 50 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 127,
    answers: [{ label: 'odległość', value: '950 km' }],
    question: 'WARSZAWA -> KISZYNIÓW',
    hints: [{ id: '127-0', label: 'WARSZAWA -> KISZYNIÓW', content: 'Można się pomylić o 65 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 128,
    answers: [{ label: 'odległość', value: '1100 km' }],
    question: 'WARSZAWA -> BUKARESZT',
    hints: [{ id: '128-0', label: 'WARSZAWA -> BUKARESZT', content: 'Można się pomylić o 75 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 129,
    answers: [{ label: 'odległość', value: '1500 km' }],
    question: 'WARSZAWA -> SOFIA',
    hints: [{ id: '129-0', label: 'WARSZAWA -> SOFIA', content: 'Można się pomylić o 100 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 130,
    answers: [{ label: 'odległość', value: '2350 km' }],
    question: 'WARSZAWA -> ATENY',
    hints: [{ id: '130-0', label: 'WARSZAWA -> ATENY', content: 'Można się pomylić o 160 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 131,
    answers: [{ label: 'odległość', value: '450 km' }],
    question: 'STAMBUŁ -> ANKARA',
    hints: [{ id: '131-0', label: 'STAMBUŁ -> ANKARA', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 132,
    answers: [{ label: 'odległość', value: '620 km' }],
    question: 'MADRYT -> BARCELONA',
    hints: [{ id: '132-0', label: 'MADRYT -> BARCELONA', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 133,
    answers: [{ label: 'odległość', value: '580 km' }],
    question: 'RZYM -> MEDIOLAN',
    hints: [{ id: '133-0', label: 'RZYM -> MEDIOLAN', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 134,
    answers: [{ label: 'odległość', value: '800 km' }],
    question: 'MONACHIUM -> HAMBURG',
    hints: [{ id: '134-0', label: 'MONACHIUM -> HAMBURG', content: 'Można się pomylić o 55 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 135,
    answers: [{ label: 'odległość', value: '460 km' }],
    question: 'PARYŻ -> LYON',
    hints: [{ id: '135-0', label: 'PARYŻ -> LYON', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 136,
    answers: [{ label: 'odległość', value: '1050 km' }],
    question: 'BERLIN -> PARYŻ',
    hints: [{ id: '136-0', label: 'BERLIN -> PARYŻ', content: 'Można się pomylić o 70 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 137,
    answers: [{ label: 'odległość', value: '1270 km' }],
    question: 'PARYŻ -> MADRYT',
    hints: [{ id: '137-0', label: 'PARYŻ -> MADRYT', content: 'Można się pomylić o 85 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 138,
    answers: [{ label: 'odległość', value: '350 km' }],
    question: 'WIEDEŃ -> BUDAPESZT',
    hints: [{ id: '138-0', label: 'WIEDEŃ -> BUDAPESZT', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 139,
    answers: [{ label: 'odległość', value: '1100 km' }],
    question: 'LONDYN -> BERLIN',
    hints: [{ id: '139-0', label: 'LONDYN -> BERLIN', content: 'Można się pomylić o 75 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 140,
    answers: [{ label: 'odległość', value: '210 km' }],
    question: 'AMSTERDAM -> BRUKSELA',
    hints: [{ id: '140-0', label: 'AMSTERDAM -> BRUKSELA', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 141,
    answers: [{ label: 'odległość', value: '500 km' }],
    question: 'MADRYT -> LIZBONA',
    hints: [{ id: '141-0', label: 'MADRYT -> LIZBONA', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 142,
    answers: [{ label: 'odległość', value: '600 km' }],
    question: 'SZTOKHOLM -> OSLO',
    hints: [{ id: '142-0', label: 'SZTOKHOLM -> OSLO', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 143,
    answers: [{ label: 'odległość', value: '1000 km' }],
    question: 'BARCELONA -> MEDIOLAN',
    hints: [{ id: '143-0', label: 'BARCELONA -> MEDIOLAN', content: 'Można się pomylić o 70 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 144,
    answers: [{ label: 'odległość', value: '400 km' }],
    question: 'HAMBURG -> KOPENHAGA',
    hints: [{ id: '144-0', label: 'HAMBURG -> KOPENHAGA', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 145,
    answers: [{ label: 'odległość', value: '310 km' }],
    question: 'RYGA -> TALLINN',
    hints: [{ id: '145-0', label: 'RYGA -> TALLINN', content: 'Można się pomylić o 22 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 146,
    answers: [{ label: 'odległość', value: '550 km' }],
    question: 'STAMBUŁ -> SOFIA',
    hints: [{ id: '146-0', label: 'STAMBUŁ -> SOFIA', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 147,
    answers: [{ label: 'odległość', value: '530 km' }],
    question: 'DUBLIN -> LONDYN',
    hints: [{ id: '147-0', label: 'DUBLIN -> LONDYN', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 148,
    answers: [{ label: 'odległość', value: '300 km' }],
    question: 'LIZBONA -> PORTO',
    hints: [{ id: '148-0', label: 'LIZBONA -> PORTO', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 149,
    answers: [{ label: 'odległość', value: '250 km' }],
    question: 'ZURYCH -> GENEWA',
    hints: [{ id: '149-0', label: 'ZURYCH -> GENEWA', content: 'Można się pomylić o 18 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 150,
    answers: [{ label: 'odległość', value: '450 km' }],
    question: 'OSLO -> BERGEN',
    hints: [{ id: '150-0', label: 'OSLO -> BERGEN', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 151,
    answers: [{ label: 'odległość', value: '150 km' }],
    question: 'BRUKSELA -> LUKSEMBURG',
    hints: [{ id: '151-0', label: 'BRUKSELA -> LUKSEMBURG', content: 'Można się pomylić o 10 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 152,
    answers: [{ label: 'odległość', value: '380 km' }],
    question: 'KOPENHAGA -> SZTOKHOLM',
    hints: [{ id: '152-0', label: 'KOPENHAGA -> SZTOKHOLM', content: 'Można się pomylić o 28 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 153,
    answers: [{ label: 'odległość', value: '250 km' }],
    question: 'HELSINKI -> TALLINN',
    hints: [{ id: '153-0', label: 'HELSINKI -> TALLINN', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 154,
    answers: [{ label: 'odległość', value: '750 km' }],
    question: 'PRAGA -> BUDAPESZT',
    hints: [{ id: '154-0', label: 'PRAGA -> BUDAPESZT', content: 'Można się pomylić o 50 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 155,
    answers: [{ label: 'odległość', value: '1100 km' }],
    question: 'BUKARESZT -> ATENY',
    hints: [{ id: '155-0', label: 'BUKARESZT -> ATENY', content: 'Można się pomylić o 75 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 156,
    answers: [{ label: 'odległość', value: '550 km' }],
    question: 'PRAGA -> MONACHIUM',
    hints: [{ id: '156-0', label: 'PRAGA -> MONACHIUM', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 157,
    answers: [{ label: 'odległość', value: '230 km' }],
    question: 'WILNO -> RYGA',
    hints: [{ id: '157-0', label: 'WILNO -> RYGA', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 158,
    answers: [{ label: 'odległość', value: '880 km' }],
    question: 'PARYŻ -> MARSYLIA',
    hints: [{ id: '158-0', label: 'PARYŻ -> MARSYLIA', content: 'Można się pomylić o 60 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 159,
    answers: [{ label: 'odległość', value: '1100 km' }],
    question: 'BARCELONA -> PARYŻ',
    hints: [{ id: '159-0', label: 'BARCELONA -> PARYŻ', content: 'Można się pomylić o 75 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 160,
    answers: [{ label: 'odległość', value: '300 km' }],
    question: 'WIEDEŃ -> PRAGA',
    hints: [{ id: '160-0', label: 'WIEDEŃ -> PRAGA', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 161,
    answers: [{ label: 'odległość', value: '640 km' }],
    question: 'RZYM -> MONACHIUM',
    hints: [{ id: '161-0', label: 'RZYM -> MONACHIUM', content: 'Można się pomylić o 45 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 162,
    answers: [{ label: 'odległość', value: '940 km' }],
    question: 'MADRYT -> SEWILLA',
    hints: [{ id: '162-0', label: 'MADRYT -> SEWILLA', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 163,
    answers: [{ label: 'odległość', value: '1600 km' }],
    question: 'LONDYN -> RZYM',
    hints: [{ id: '163-0', label: 'LONDYN -> RZYM', content: 'Można się pomylić o 110 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 164,
    answers: [{ label: 'odległość', value: '1100 km' }],
    question: 'MEDIOLAN -> NEAPOL',
    hints: [{ id: '164-0', label: 'MEDIOLAN -> NEAPOL', content: 'Można się pomylić o 55 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 165,
    answers: [{ label: 'odległość', value: '750 km' }],
    question: 'BERLIN -> MONACHIUM',
    hints: [{ id: '165-0', label: 'BERLIN -> MONACHIUM', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 166,
    answers: [{ label: 'odległość', value: '400 km' }],
    question: 'ZAGRZEB -> LUBIANA',
    hints: [{ id: '166-0', label: 'ZAGRZEB -> LUBIANA', content: 'Można się pomylić o 10 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 167,
    answers: [{ label: 'odległość', value: '600 km' }],
    question: 'WROCŁAW -> PRAGA',
    hints: [{ id: '167-0', label: 'WROCŁAW -> PRAGA', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 168,
    answers: [{ label: 'odległość', value: '330 km' }],
    question: 'BRATYSŁAWA -> BUDAPESZT',
    hints: [{ id: '168-0', label: 'BRATYSŁAWA -> BUDAPESZT', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 169,
    answers: [{ label: 'odległość', value: '250 km' }],
    question: 'KRAKÓW -> OSTRAWA',
    hints: [{ id: '169-0', label: 'KRAKÓW -> OSTRAWA', content: 'Można się pomylić o 12 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 170,
    answers: [{ label: 'odległość', value: '480 km' }],
    question: 'GDAŃSK -> KALININGRAD',
    hints: [{ id: '170-0', label: 'GDAŃSK -> KALININGRAD', content: 'Można się pomylić o 12 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 171,
    answers: [{ label: 'odległość', value: '330 km' }],
    question: 'MEDIOLAN -> WENECJA',
    hints: [{ id: '171-0', label: 'MEDIOLAN -> WENECJA', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 172,
    answers: [{ label: 'odległość', value: '450 km' }],
    question: 'LONDYN -> PARYŻ',
    hints: [{ id: '172-0', label: 'LONDYN -> PARYŻ', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 173,
    answers: [{ label: 'odległość', value: '1200 km' }],
    question: 'BARCELONA -> SEWILLA',
    hints: [{ id: '173-0', label: 'BARCELONA -> SEWILLA', content: 'Można się pomylić o 70 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 174,
    answers: [{ label: 'odległość', value: '300 km' }],
    question: 'MONACHIUM -> SALZBURG',
    hints: [{ id: '174-0', label: 'MONACHIUM -> SALZBURG', content: 'Można się pomylić o 10 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 175,
    answers: [{ label: 'odległość', value: '780 km' }],
    question: 'AMSTERDAM -> BERLIN',
    hints: [{ id: '175-0', label: 'AMSTERDAM -> BERLIN', content: 'Można się pomylić o 50 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 176,
    answers: [{ label: 'odległość', value: '470 km' }],
    question: 'LYON -> MARSYLIA',
    hints: [{ id: '176-0', label: 'LYON -> MARSYLIA', content: 'Można się pomylić o 25 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 177,
    answers: [{ label: 'odległość', value: '1800 km' }],
    question: 'ATENY -> STAMBUŁ',
    hints: [{ id: '177-0', label: 'ATENY -> STAMBUŁ', content: 'Można się pomylić o 80 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 178,
    answers: [{ label: 'odległość', value: '250 km' }],
    question: 'GLASGOW -> EDYNBURG',
    hints: [{ id: '178-0', label: 'GLASGOW -> EDYNBURG', content: 'Można się pomylić o 5 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 179,
    answers: [{ label: 'odległość', value: '520 km' }],
    question: 'PRAGA -> WIEDEŃ',
    hints: [{ id: '179-0', label: 'PRAGA -> WIEDEŃ', content: 'Można się pomylić o 20 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 180,
    answers: [{ label: 'odległość', value: '1100 km' }],
    question: 'RZYM -> PALERMO',
    hints: [{ id: '180-0', label: 'RZYM -> PALERMO', content: 'Można się pomylić o 65 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 181,
    answers: [{ label: 'odległość', value: '1550 km' }],
    question: 'MADRYT -> PARYŻ',
    hints: [{ id: '181-0', label: 'MADRYT -> PARYŻ', content: 'Można się pomylić o 90 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 182,
    answers: [{ label: 'odległość', value: '600 km' }],
    question: 'FRANKFURT -> MONACHIUM',
    hints: [{ id: '182-0', label: 'FRANKFURT -> MONACHIUM', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 183,
    answers: [{ label: 'odległość', value: '480 km' }],
    question: 'OSLO -> SZTOKHOLM',
    hints: [{ id: '183-0', label: 'OSLO -> SZTOKHOLM', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 184,
    answers: [{ label: 'odległość', value: '3000 km' }],
    question: 'LIZBONA -> SZTOKHOLM',
    hints: [{ id: '184-0', label: 'LIZBONA -> SZTOKHOLM', content: 'Można się pomylić o 200 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 185,
    answers: [{ label: 'odległość', value: '800 km' }],
    question: 'ZURYCH -> WIEDEŃ',
    hints: [{ id: '185-0', label: 'ZURYCH -> WIEDEŃ', content: 'Można się pomylić o 50 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 186,
    answers: [{ label: 'odległość', value: '100 km' }],
    question: 'MALTA (VALLETTA) -> SYRAKUZY',
    hints: [{ id: '186-0', label: 'VALLETTA -> SYRAKUZY', content: 'Można się pomylić o 10 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 187,
    answers: [{ label: 'odległość', value: '500 km' }],
    question: 'KOPENHAGA -> OSLO',
    hints: [{ id: '187-0', label: 'KOPENHAGA -> OSLO', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 188,
    answers: [{ label: 'odległość', value: '2500 km' }],
    question: 'ATENY -> LONDYN',
    hints: [{ id: '188-0', label: 'ATENY -> LONDYN', content: 'Można się pomylić o 180 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 189,
    answers: [{ label: 'odległość', value: '450 km' }],
    question: 'BUDAPESZT -> BELGRAD',
    hints: [{ id: '189-0', label: 'BUDAPESZT -> BELGRAD', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 190,
    answers: [{ label: 'odległość', value: '1100 km' }],
    question: 'NICEA -> RZYM',
    hints: [{ id: '190-0', label: 'NICEA -> RZYM', content: 'Można się pomylić o 50 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 191,
    answers: [{ label: 'odległość', value: '1300 km' }],
    question: 'HAMBURG -> MEDIOLAN',
    hints: [{ id: '191-0', label: 'HAMBURG -> MEDIOLAN', content: 'Można się pomylić o 80 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 192,
    answers: [{ label: 'odległość', value: '280 km' }],
    question: 'ANKARA -> KONYA',
    hints: [{ id: '192-0', label: 'ANKARA -> KONYA', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 193,
    answers: [{ label: 'odległość', value: '1700 km' }],
    question: 'MADRYT -> AMSTERDAM',
    hints: [{ id: '193-0', label: 'MADRYT -> AMSTERDAM', content: 'Można się pomylić o 120 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 194,
    answers: [{ label: 'odległość', value: '600 km' }],
    question: 'RYGA -> HELSINKI',
    hints: [{ id: '194-0', label: 'RYGA -> HELSINKI', content: 'Można się pomylić o 35 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 195,
    answers: [{ label: 'odległość', value: '950 km' }],
    question: 'SARAJEWO -> WIEDEŃ',
    hints: [{ id: '195-0', label: 'SARAJEWO -> WIEDEŃ', content: 'Można się pomylić o 60 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 196,
    answers: [{ label: 'odległość', value: '250 km' }],
    question: 'KOLONIA -> FRANKFURT',
    hints: [{ id: '196-0', label: 'KOLONIA -> FRANKFURT', content: 'Można się pomylić o 15 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 197,
    answers: [{ label: 'odległość', value: '1400 km' }],
    question: 'BARCELONA -> LIZBONA',
    hints: [{ id: '197-0', label: 'BARCELONA -> LIZBONA', content: 'Można się pomylić o 80 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 198,
    answers: [{ label: 'odległość', value: '450 km' }],
    question: 'TALLINN -> SZTOKHOLM',
    hints: [{ id: '198-0', label: 'TALLINN -> SZTOKHOLM', content: 'Można się pomylić o 30 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 199,
    answers: [{ label: 'odległość', value: '2100 km' }],
    question: 'REYKJAVIK -> LONDYN',
    hints: [{ id: '199-0', label: 'REYKJAVIK -> LONDYN', content: 'Można się pomylić o 150 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  },
  {
    id: 200,
    answers: [{ label: 'odległość', value: '850 km' }],
    question: 'MONACHIUM -> WENECJA',
    hints: [{ id: '200-0', label: 'MONACHIUM -> WENECJA', content: 'Można się pomylić o 40 km', penaltyPercent: 0 }],
    revealedAnswers: [],
  }
];
