export const KLUBOWE_PRZYDOMKI = [
  {
    id: 0,
    question: 'Kanonierzy',
    answers: [{ label: 'Klub', value: 'Arsenal Londyn' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 1,
    question: 'The Reds (Czerwoni)',
    answers: [{ label: 'Klub', value: 'Liverpool FC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 2,
    question: 'Czerwone Diabły',
    answers: [{ label: 'Klub', value: 'Manchester United' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 3,
    question: 'The Blues (Niebiescy)',
    answers: [{ label: 'Klub', value: 'Chelsea Londyn' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 4,
    question: 'The Citizens (Obywatele)',
    answers: [{ label: 'Klub', value: 'Manchester City' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 5,
    question: 'Królewscy',
    answers: [{ label: 'Klub', value: 'Real Madryt' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 6,
    question: 'Duma Katalonii (Blaugrana)',
    answers: [{ label: 'Klub', value: 'FC Barcelona' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 7,
    question: 'Los Colchoneros (Materace)',
    answers: [{ label: 'Klub', value: 'Atletico Madryt' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 8,
    question: 'Bawarczycy',
    answers: [{ label: 'Klub', value: 'Bayern Monachium' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 9,
    question: 'Aptekarze',
    answers: [{ label: 'Klub', value: 'Bayer Leverkusen' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 10,
    question: 'Stara Dama',
    answers: [{ label: 'Klub', value: 'Juventus Turyn' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 11,
    question: 'Rossoneri',
    answers: [{ label: 'Klub', value: 'AC Milan' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 12,
    question: 'Nerazzurri',
    answers: [{ label: 'Klub', value: 'Inter Mediolan' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 13,
    question: 'Giallorossi (Żółto-czerwoni)',
    answers: [{ label: 'Klub', value: 'AS Roma' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 14,
    question: 'The Spurs (Koguty)',
    answers: [{ label: 'Klub', value: 'Tottenham Hotspur' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 15,
    question: 'The Toffees (The Ev)',
    answers: [{ label: 'Klub', value: 'Everton FC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 16,
    question: 'Papiery (The Hammers)',
    answers: [{ label: 'Klub', value: 'West Ham United' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 17,
    question: 'Sroki (The Magpies)',
    answers: [{ label: 'Klub', value: 'Newcastle United' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 18,
    question: 'Wilki (Wolves)',
    answers: [{ label: 'Klub', value: 'Wolverhampton Wanderers' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 19,
    question: 'Pszczoły (The Bees)',
    answers: [{ label: 'Klub', value: 'Brentford FC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 20,
    question: 'Mewy (The Seagulls)',
    answers: [{ label: 'Klub', value: 'Brighton & Hove Albion' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 21,
    question: 'Wieśniaki (Die Kraichgauer)',
    answers: [{ label: 'Klub', value: 'TSG 1899 Hoffenheim' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 22,
    question: 'Die Borussen',
    answers: [{ label: 'Klub', value: 'Borussia Dortmund' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 23,
    question: 'Orły (Die Adler)',
    answers: [{ label: 'Klub', value: 'Eintracht Frankfurt' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 24,
    question: 'Kozły (Die Geißböcke)',
    answers: [{ label: 'Klub', value: '1. FC Köln' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 25,
    question: 'Źrebaki (Die Fohlen)',
    answers: [{ label: 'Klub', value: 'Borussia Mönchengladbach' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 26,
    question: 'Nietoperze (Los Che)',
    answers: [{ label: 'Klub', value: 'Valencia CF' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 27,
    question: 'Żółta Łódź Podwodna',
    answers: [{ label: 'Klub', value: 'Villarreal CF' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 28,
    question: 'Papużki (Los Pericos)',
    answers: [{ label: 'Klub', value: 'Espanyol Barcelona' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 29,
    question: 'Lwy (Les Lions)',
    answers: [{ label: 'Klub', value: 'Olympique Lyon' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 30,
    question: 'Les Parisiens',
    answers: [{ label: 'Klub', value: 'Paris Saint-Germain' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 31,
    question: 'Smoki (Os Dragões)',
    answers: [{ label: 'Klub', value: 'FC Porto' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 32,
    question: 'Orły (As Águias)',
    answers: [{ label: 'Klub', value: 'SL Benfica' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 33,
    question: 'Lwy (Os Leões)',
    answers: [{ label: 'Klub', value: 'Sporting CP' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 34,
    question: 'Godenzonen (Synowie Bogów)',
    answers: [{ label: 'Klub', value: 'Ajax Amsterdam' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 35,
    question: 'Rolnicy (Boeren)',
    answers: [{ label: 'Klub', value: 'PSV Eindhoven' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 36,
    question: 'Wojskowi',
    answers: [{ label: 'Klub', value: 'Legia Warszawa' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 37,
    question: 'Kolejorz',
    answers: [{ label: 'Klub', value: 'Lech Poznań' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 38,
    question: 'Biała Gwiazda',
    answers: [{ label: 'Klub', value: 'Wisła Kraków' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 39,
    question: 'Pasy',
    answers: [{ label: 'Klub', value: 'Cracovia' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 40,
    question: 'Niebiescy',
    answers: [{ label: 'Klub', value: 'Ruch Chorzów' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 41,
    question: 'Medalikowicze',
    answers: [{ label: 'Klub', value: 'Raków Częstochowa' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 42,
    question: 'Portowcy',
    answers: [{ label: 'Klub', value: 'Pogoń Szczecin' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 43,
    question: 'Jaga',
    answers: [{ label: 'Klub', value: 'Jagiellonia Białystok' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 44,
    question: 'Miedziowi',
    answers: [{ label: 'Klub', value: 'Zagłębie Lubin' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 45,
    question: 'Zieloni',
    answers: [{ label: 'Klub', value: 'Warta Poznań' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 46,
    question: 'Słonie',
    answers: [{ label: 'Klub', value: 'Bruk-Bet Termalica Nieciecza' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 47,
    question: 'Żabole',
    answers: [{ label: 'Klub', value: 'Górnik Zabrze' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 48,
    question: 'Górale',
    answers: [{ label: 'Klub', value: 'Podbeskidzie Bielsko-Biała' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 49,
    question: 'Żółto-Niebiescy',
    answers: [{ label: 'Klub', value: 'Arka Gdynia' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 50,
    question: 'Rycerze Wiosny',
    answers: [{ label: 'Klub', value: 'ŁKS Łódź' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 51,
    question: 'Blaugrana',
    answers: [{ label: 'Klub', value: 'FC Barcelona' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 52,
    question: 'The Cherries (Wisienki)',
    answers: [{ label: 'Klub', value: 'AFC Bournemouth' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 53,
    question: 'The Villans',
    answers: [{ label: 'Klub', value: 'Aston Villa' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 54,
    question: 'The Cottagers',
    answers: [{ label: 'Klub', value: 'Fulham FC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 55,
    question: 'The Foxes (Lisy)',
    answers: [{ label: 'Klub', value: 'Leicester City' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 56,
    question: 'The Blades (Szable)',
    answers: [{ label: 'Klub', value: 'Sheffield United' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 57,
    question: 'The Black Cats (Czarne Koty)',
    answers: [{ label: 'Klub', value: 'Sunderland AFC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 58,
    question: 'The Lions (Lwy)',
    answers: [{ label: 'Klub', value: 'Millwall FC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 59,
    question: 'The Owls (Sowy)',
    answers: [{ label: 'Klub', value: 'Sheffield Wednesday' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 60,
    question: 'The Rams (Barany)',
    answers: [{ label: 'Klub', value: 'Derby County' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 61,
    question: 'La Dea (Bogini)',
    answers: [{ label: 'Klub', value: 'Atalanta Bergamo' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 62,
    question: 'Viola (Fiołki)',
    answers: [{ label: 'Klub', value: 'ACF Fiorentina' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 63,
    question: 'Biancocelesti (Biało-błękitni)',
    answers: [{ label: 'Klub', value: 'Lazio Rzym' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 64,
    question: 'Azzurri (Błękitni)',
    answers: [{ label: 'Klub', value: 'SSC Napoli' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 65,
    question: 'I Blucerchiati',
    answers: [{ label: 'Klub', value: 'Sampdoria Genua' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 66,
    question: 'Toro (Byki)',
    answers: [{ label: 'Klub', value: 'Torino FC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 67,
    question: 'Los Merengues (Bezy)',
    answers: [{ label: 'Klub', value: 'Real Madryt' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 68,
    question: 'Los Palanganas',
    answers: [{ label: 'Klub', value: 'Sevilla FC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 69,
    question: 'Los Beticos',
    answers: [{ label: 'Klub', value: 'Betis Sewilla' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 70,
    question: 'Los Leones (Lwy)',
    answers: [{ label: 'Klub', value: 'Athletic Bilbao' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 71,
    question: 'Die Knappen (Górnicy)',
    answers: [{ label: 'Klub', value: 'Schalke 04 Gelsenkirchen' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 72,
    question: 'Die Werkself',
    answers: [{ label: 'Klub', value: 'Bayer Leverkusen' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 73,
    question: 'Die Roten Bullen (Czerwone Byki)',
    answers: [{ label: 'Klub', value: 'RB Lipsk' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 74,
    question: 'Les Canaris (Kanarki)',
    answers: [{ label: 'Klub', value: 'FC Nantes' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 75,
    question: 'Les Dogues (Mastify)',
    answers: [{ label: 'Klub', value: 'Lille OSC' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 76,
    question: 'Les Verts (Zieloni)',
    answers: [{ label: 'Klub', value: 'AS Saint-Étienne' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 77,
    question: 'Les Phocéens (Fokejczycy)',
    answers: [{ label: 'Klub', value: 'Olympique Marsylia' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 78,
    question: 'Xeneizes',
    answers: [{ label: 'Klub', value: 'Boca Juniors' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 79,
    question: 'Los Millonarios (Milionerzy)',
    answers: [{ label: 'Klub', value: 'River Plate' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 80,
    question: 'Ursaici (Niedźwiadki)',
    answers: [{ label: 'Klub', value: 'Atletico Madryt' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 81,
    question: 'Cidry',
    answers: [{ label: 'Klub', value: 'Ruch Radzionków' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 82,
    question: 'Duma Podlasia',
    answers: [{ label: 'Klub', value: 'Jagiellonia Białystok' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 83,
    question: 'Duma Stolicy',
    answers: [{ label: 'Klub', value: 'Polonia Warszawa' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 84,
    question: 'Sączersi',
    answers: [{ label: 'Klub', value: 'Sandecja Nowy Sącz' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 85,
    question: 'Stalówka',
    answers: [{ label: 'Klub', value: 'Stal Stalowa Wola' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 86,
    question: 'Brunatni',
    answers: [{ label: 'Klub', value: 'GKS Bełchatów' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 87,
    question: 'Czarne Koszule',
    answers: [{ label: 'Klub', value: 'Polonia Warszawa' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 88,
    question: 'Okocimscy (Piwosze)',
    answers: [{ label: 'Klub', value: 'Okocimski KS Brzesko' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 89,
    question: 'Biało-Zieloni',
    answers: [{ label: 'Klub', value: 'Lechia Gdańsk' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 90,
    question: 'Konińskie Aluminium',
    answers: [{ label: 'Klub', value: 'Aluminium Konin' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 91,
    question: 'Biała Armia',
    answers: [{ label: 'Klub', value: 'Motor Lublin' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 92,
    question: 'GieKSa',
    answers: [{ label: 'Klub', value: 'GKS Katowice' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 93,
    question: 'Chłopcy z Reymonta',
    answers: [{ label: 'Klub', value: 'Wisła Kraków' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 94,
    question: 'Duma Pomorza',
    answers: [{ label: 'Klub', value: 'Pogoń Szczecin' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 95,
    question: 'Żółto-Czerwoni',
    answers: [{ label: 'Klub', value: 'Korona Kielce' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 96,
    question: 'Legioniści',
    answers: [{ label: 'Klub', value: 'Legia Warszawa' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 97,
    question: 'Biało-Niebiesko-Czerwoni',
    answers: [{ label: 'Klub', value: 'Miedź Legnica' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 98,
    question: 'Olimpijczycy',
    answers: [{ label: 'Klub', value: 'Olimpia Elbląg' }],
    showAnswer: false,
    revealedAnswers: [],
  },
  {
    id: 99,
    question: 'Kurczaki',
    answers: [{ label: 'Klub', value: 'Piast Gliwice' }],
    showAnswer: false,
    revealedAnswers: [],
  },
];
