export const MECZE_PILKARSKIE = [
  {
    id: 1,
    question: ' Piast Gliwice 1-1 Jagiellonia Białystok ( 13.09.2025 ) Ekstraklasa 2025/2026',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'PLach', position: 1, country: 'PL'},
              {surname: 'Twumasi', position: 2, country: 'GH'},
              {surname: 'Drapiński', position: 3, country: 'PL'},
              {surname: 'Czerwiński', position: 4, country: 'PL'},
              {surname: 'Tomasiewicz', position: 5, country: 'PL'},
              {surname: 'Dziczek', position: 6, country: 'PL'},
              {surname: 'Boisgard', position: 7, country: 'FR'},
              {surname: 'Chrapek', position: 8, country: 'PL'},
              {surname: 'Sanca', position: 9, country: 'GW'},
              {surname: 'Jirka', position: 10, country: 'SK'},
              {surname: 'Felix', position: 11, country: 'ES'},
            ],
            substitutes: [
              {surname: 'Dalmau', position: 15, country: 'ES'},
              {surname: 'Barkovskiy', position: 16, country: 'BY'},
              {surname: 'Lokilo', position: 17, country: 'CD'},
              {surname: 'Leśniak', position: 18, country: 'PL'},
              {surname: 'Rivas', position: 19, country: 'ES'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Abramowicz', position: 1, country: 'PL'},
              {surname: 'Wdowik', position: 2, country: 'PL'},
              {surname: 'Stojinovic', position: 3, country: 'SI'},
              {surname: 'Vital', position: 4, country: 'PR'},
              {surname: 'Wojtuszek', position: 5, country: 'PL'},
              {surname: 'Romanczuk', position: 6, country: 'PL'},
              {surname: 'Imaz', position: 7, country: 'ES'},
              {surname: 'Drachal', position: 8, country: 'PL'},
              {surname: 'Pietuszewski', position: 9, country: 'PL'},
              {surname: 'Pululu', position: 10, country: 'CD'},
              {surname: 'Pozo', position: 11, country: 'ES'},
            ],
            substitutes: [
              {surname: 'Rallis', position: 15, country: 'GR'},
              {surname: 'Jóźwiak', position: 16, country: 'PL'},
              {surname: 'Jackson', position: 17, country: 'US'},
              {surname: 'Lozano', position: 17, country: 'ES'},
              {surname: 'Kobayashi', position: 17, country: 'JP'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 2,
    question: ' Piast Gliwice 4-0 Lech Poznań ( 15.02.2019 ) Ekstraklasa 2018/2019',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Plach', position: 1, country: 'SK'},
              {surname: 'Kirkeskov', position: 2, country: 'DK'},
              {surname: 'Czerwiński', position: 3, country: 'PL'},
              {surname: 'Sedlar', position: 4, country: 'RS'},
              {surname: 'Pietrowski', position: 5, country: 'PL'},
              {surname: 'Dziczek', position: 6, country: 'PL'},
              {surname: 'Hateley', position: 7, country: 'EN'},
              {surname: 'Felix', position: 8, country: 'ES'},
              {surname: 'Valencia', position: 9, country: 'EC'},
              {surname: 'Parzyszek', position: 10, country: 'PL'},
              {surname: 'Konczkowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Jodłowiec', position: 15, country: 'PL'},
              {surname: 'Badia', position: 16, country: 'ES'},
              {surname: 'Papadopulos', position: 17, country: 'CZ'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Buric', position: 1, country: 'BA'},
              {surname: 'Kostevych', position: 2, country: 'UA'},
              {surname: 'Vujadinovic', position: 3, country: 'ME'},
              {surname: 'Janicki', position: 4, country: 'PL'},
              {surname: 'Wasilewski', position: 5, country: 'PL'},
              {surname: 'Trałka', position: 6, country: 'PL'},
              {surname: 'Tiba', position: 7, country: 'PT'},
              {surname: 'Jevtic', position: 8, country: 'CH'},
              {surname: 'Amaral', position: 9, country: 'PT'},
              {surname: 'Gytkjaer', position: 10, country: 'DK'},
              {surname: 'Klupś', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Gajos', position: 15, country: 'PL'},
              {surname: 'Jóźwiak', position: 16, country: 'PL'},
              {surname: 'Zhamaletdinov', position: 17, country: 'RU'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 3,
    question: 'Piast Gliwice 0-1 Zagłębie Lubin  (15.05.2016) Ekstraklasa 2015/2016',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          firstTeam: {
            formation: '1-3-5-2',
            footballers: [
              {surname: 'Szmatuła', position: 1, country: 'PL'},
              {surname: 'Pietrowski', position: 2, country: 'PL'},
              {surname: 'Hebert', position: 3, country: 'BR'},
              {surname: 'Korun', position: 4, country: 'SK'},
              {surname: 'Vacek', position: 5, country: 'CZ'},
              {surname: 'Murawski', position: 6, country: 'PL'},
              {surname: 'Živec', position: 7, country: 'SK'},
              {surname: 'Bukata', position: 8, country: 'SK'},
              {surname: 'Mraz', position: 9, country: 'SK'},
              {surname: 'Barisic', position: 10, country: 'HR'},
              {surname: 'Nespor', position: 11, country: 'CZ'},
            ],
            substitutes: [
              {surname: 'Mak', position: 15, country: 'PL'},
              {surname: 'Badia', position: 16, country: 'ES'},
              {surname: 'Szeliga', position: 17, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Polacek', position: 1, country: 'SK'},
              {surname: 'Todorowski', position: 2, country: 'MK '},
              {surname: 'Dabrowski', position: 3, country: 'PL'},
              {surname: 'Jach', position: 4, country: 'PL'},
              {surname: 'Cotra', position: 5, country: 'RS'},
              {surname: 'Tosik', position: 6, country: 'PL'},
              {surname: 'Piątek', position: 7, country: 'PL'},
              {surname: 'Starzyński', position: 8, country: 'PL'},
              {surname: 'Janoszka', position: 9, country: 'PL'},
              {surname: 'Woźniak', position: 10, country: 'PL'},
              {surname: 'Papadopulos', position: 11, country: 'CZ'},
            ],
            substitutes: [
              {surname: 'Piątek', position: 15, country: 'PL'},
              {surname: 'Rakowski', position: 16, country: 'PL'},
              {surname: 'Zbozień', position: 17, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 4,
    question: 'Real Madryt 3-1 Manchaster City (04.05.2022) Liga Mistrzów  2021/2022',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: ' ',
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Courtois', position: 1, country: 'BE'},
              {surname: 'Mendy', position: 2, country: 'FR'},
              {surname: 'Fernández', position: 3, country: 'ES'},
              {surname: 'Militão', position: 4, country: 'BR'},
              {surname: 'Carvajal', position: 5, country: 'ES'},
              {surname: 'Casemiro', position: 6, country: 'BR'},
              {surname: 'Kroos', position: 7, country: 'DE'},
              {surname: 'Vinicius', position: 8, country: 'BR'},
              {surname: 'Modrić', position: 9, country: 'HR'},
              {surname: 'Valverde', position: 10, country: 'UY'},
              {surname: 'Benzema', position: 11, country: 'FR'},
            ],
            substitutes: [
              {surname: 'Vallejo', position: 12, country: 'ES'},
              {surname: 'Vázquez', position: 13, country: 'ES'},
              {surname: 'Camavinga', position: 14, country: 'FR'},
              {surname: 'Ceballos', position: 15, country: 'ES'},
              {surname: 'Asensio', position: 16, country: 'ES'},
              {surname: 'Rodrygo', position: 17, country: 'BR'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Ederson', position: 1, country: 'BR'},
              {surname: 'Cancelo', position: 2, country: 'PT '},
              {surname: 'Laporte', position: 3, country: 'ES'},
              {surname: 'Dias', position: 4, country: 'PT'},
              {surname: 'Walker', position: 5, country: 'EN'},
              {surname: 'Rodri', position: 6, country: 'ES'},
              {surname: 'De Bruyne', position: 7, country: 'BE'},
              {surname: 'Silva', position: 8, country: 'EN'},
              {surname: 'Foden', position: 9, country: 'EN'},
              {surname: 'Jesus', position: 10, country: 'BR'},
              {surname: 'Mahrez', position: 11, country: 'DZ'},
            ],
            substitutes: [
              {surname: 'Fernandinho', position: 12, country: 'BR'},
              {surname: 'Gündoğan', position: 13, country: 'DE'},
              {surname: 'Grealish', position: 14, country: 'EN'},
              {surname: 'Sterling', position: 15, country: 'EN'},
              {surname: 'Zinchenko', position: 16, country: 'UA'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 5,
    question: 'Real Madryt 1-4 Ajax Amsterdam (05.03.2019) Liga mistrzów 2018/2019',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: ' ',
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Courtois', position: 1, country: 'BE'},
              {surname: 'Regulion', position: 2, country: 'ES'},
              {surname: 'Fernández', position: 3, country: 'ES'},
              {surname: 'Varane', position: 4, country: 'FR'},
              {surname: 'Carvajal', position: 5, country: 'ES'},
              {surname: 'Casemiro', position: 6, country: 'BR'},
              {surname: 'Kroos', position: 7, country: 'DE'},
              {surname: 'Modrić', position: 8, country: 'HR'},
              {surname: 'Vinicius', position: 9, country: 'BR'},
              {surname: 'Vazquez', position: 10, country: 'ES'},
              {surname: 'Benzema', position: 11, country: 'FR'},
            ],
            substitutes: [
              {surname: 'Valverde', position: 12, country: 'UY'},
              {surname: 'Bale', position: 13, country: 'WLS'},
              {surname: 'Asensio', position: 16, country: 'ES'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Onana', position: 1, country: 'CM'},
              {surname: 'Tagliafico', position: 2, country: 'AR'},
              {surname: 'Blind', position: 3, country: 'NL'},
              {surname: 'De Ligt', position: 4, country: 'NL'},
              {surname: 'Mazraoui', position: 5, country: 'MA'},
              {surname: 'De Jong', position: 6, country: 'NL'},
              {surname: 'Schöne', position: 7, country: 'DK'},
              {surname: 'Van Fe Beek', position: 8, country: 'NL'},
              {surname: 'Neres', position: 9, country: 'BR'},
              {surname: 'Tadić', position: 10, country: 'RS'},
              {surname: 'Ziyech', position: 11, country: 'MA'},
            ],
            substitutes: [
              {surname: 'Veltman', position: 12, country: 'NL'},
              {surname: 'De Wit', position: 13, country: 'NL'},
              {surname: 'Dolberg', position: 14, country: 'DK'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 6,
    question: 'Portugalia 3-3 Hiszpania (15.06.2018) Mundial 2018',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Portugal vs Spain 3-3',
          firstTeam: {
            formation: '4-4-2',
            footballers: [
              {surname: 'Patrício', position: 1, country: 'PT'},
              {surname: 'Soares', position: 2, country: 'PT'},
              {surname: 'Pepe', position: 3, country: 'PT'},
              {surname: 'Fonte', position: 4, country: 'PT'},
              {surname: 'Guerreiro', position: 5, country: 'PT'},
              {surname: 'Carvalho', position: 6, country: 'PT'},
              {surname: 'Moutinho', position: 7, country: 'PT'},
              {surname: 'Fernandes', position: 8, country: 'PT'},
              {surname: 'Silva', position: 9, country: 'PT'},
              {surname: 'Guedes', position: 10, country: 'PT'},
              {surname: 'Ronaldo', position: 11, country: 'PT'},
            ],
            substitutes: [
              {surname: 'Mário', position: 12, country: 'PT'},
              {surname: 'Quaresma', position: 13, country: 'PT'},
              {surname: 'Silva', position: 14, country: 'PT'},
            ],
          },
          secondTeam: {
            formation: '4-3-3',
            footballers: [
              {surname: 'De Gea', position: 1, country: 'ES'},
              {surname: 'Fernández', position: 2, country: 'ES'},
              {surname: 'Piqué', position: 3, country: 'ES'},
              {surname: 'Ramos', position: 4, country: 'ES'},
              {surname: 'Alba', position: 5, country: 'ES'},
              {surname: 'Busquets', position: 6, country: 'ES'},
              {surname: 'Koke', position: 7, country: 'ES'},
              {surname: 'Iniesta', position: 8, country: 'ES'},
              {surname: 'Silva', position: 9, country: 'ES'},
              {surname: 'Isco', position: 10, country: 'ES'},
              {surname: 'Diego Costa', position: 11, country: 'ES'},
            ],
            substitutes: [
              {surname: 'Alcántara', position: 12, country: 'ES'},
              {surname: 'Aspas', position: 13, country: 'ES'},
              {surname: 'Vázquez', position: 14, country: 'ES'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 7,
    question: 'Wisła Kraków 3-4 Piast Gliwice (31.01.2021) Ekstraklasa 2020/2021',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Wisła Kraków vs Piast Gliwice 3-4',
          firstTeam: {
            formation: '4-1-4-1',
            footballers: [
              {surname: 'Buchalik', position: 1, country: 'PL'},
              {surname: 'Sadolok', position: 2, country: 'PL'},
              {surname: 'Frydrych', position: 3, country: 'CZ'},
              {surname: 'Mehremic', position: 4, country: 'BA'},
              {surname: 'Burliga', position: 5, country: 'PL'},
              {surname: 'Plewka', position: 6, country: 'PL'},
              {surname: 'Savic', position: 7, country: 'AT'},
              {surname: 'Żukow', position: 8, country: 'KZ'},
              {surname: 'Yeboah', position: 9, country: 'GH'},
              {surname: 'Silva', position: 10, country: 'BR'},
              {surname: 'Brown', position: 11, country: 'CR'},
            ],
            substitutes: [
              {surname: 'Starzyński', position: 12, country: 'PL'},
              {surname: 'Medved', position: 13, country: 'SI'},
              {surname: 'Błaszczykowski', position: 14, country: 'PL'},
              {surname: 'Boguski', position: 15, country: 'PL'},
              {surname: 'Szot', position: 16, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '4-4-1-1',
            footballers: [
              {surname: 'Plach', position: 1, country: 'SK'},
              {surname: 'Holubek', position: 2, country: 'SK'},
              {surname: 'Czerwiński', position: 3, country: 'PL'},
              {surname: 'Huk', position: 4, country: 'SK'},
              {surname: 'Konczkowski', position: 5, country: 'PL'},
              {surname: 'Chrapek', position: 6, country: 'PL'},
              {surname: 'Sokołowski', position: 7, country: 'PL'},
              {surname: 'Lipski', position: 8, country: 'PL'},
              {surname: 'Steczyk', position: 9, country: 'PL'},
              {surname: 'Badía', position: 10, country: 'ES'},
              {surname: 'Świerczok', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Jodłowiec', position: 12, country: 'PL'},
              {surname: 'Vida', position: 13, country: 'HU'},
              {surname: 'Żyro', position: 14, country: 'PL'},
              {surname: 'Milewski', position: 14, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 8,
    question: 'Piast Gliwice 3-1 Legia Warszawa (05.10.2014) Ekstraklasa 2014/2015',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Piast Gliwice 3-1 Legia Warszawa (05.10.2014) Ekstraklasa 2014/2015',
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Szmatula', position: 1, country: 'PL'},
              {surname: 'Brożek', position: 2, country: 'PL'},
              {surname: 'Horvath', position: 3, country: 'SK'},
              {surname: 'Osyra', position: 4, country: 'PL'},
              {surname: 'Klepczyński', position: 5, country: 'PL'},
              {surname: 'Martínez', position: 6, country: 'ES'},
              {surname: 'Murawski', position: 7, country: 'PL'},
              {surname: 'Jurado', position: 8, country: 'ES'},
              {surname: 'Podgórski', position: 9, country: 'PL'},
              {surname: 'Izvolt', position: 10, country: 'SK'},
              {surname: 'Wilczek', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Zivec', position: 15, country: 'SK'},
              {surname: 'Szeliga', position: 16, country: 'PL'},
              {surname: 'Hanzel', position: 17, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-5-1',
            footballers: [
              {surname: 'Kuciak', position: 1, country: 'SK'},
              {surname: 'Broź', position: 2, country: 'PL'},
              {surname: 'Astiz', position: 3, country: 'ES'},
              {surname: 'Lewczuk', position: 4, country: 'PL'},
              {surname: 'Rzeźniczak', position: 5, country: 'PL'},
              {surname: 'Bielik', position: 6, country: 'PL'},
              {surname: 'Vrdoljak', position: 7, country: 'HR'},
              {surname: 'Pinto', position: 8, country: 'PT'},
              {surname: 'Kosecki', position: 9, country: 'PL'},
              {surname: 'Saganowski', position: 10, country: 'PL'},
              {surname: 'Sá', position: 11, country: 'PT'},
            ],
            substitutes: [
              {surname: 'Jodłowiec', position: 15, country: 'PL'},
              {surname: 'Żyro', position: 16, country: 'PL'},
              {surname: 'Duda', position: 17, country: 'SK'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 9,
    question: 'Qarabag Agdam  2-1 Piast Gliwice (18.07.2013) Eliminacje Ligi Europy 2013/2014',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Qarabag Agdam 2-1 Piast Gliwice( 18.07.2013 ) Eliminacje Ligi Europy 2013/2014',
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Varvodic', position: 1, country: 'HR'},
              {surname: 'Agolli', position: 2, country: 'AL'},
              {surname: 'Sadyqov', position: 3, country: 'AZ'},
              {surname: 'Teli', position: 4, country: 'AL'},
              {surname: 'Medvedev', position: 5, country: 'AZ'},
              {surname: 'Yusifov', position: 6, country: 'AZ'},
              {surname: 'Qarayev', position: 7, country: 'AZ'},
              {surname: 'Reynaldo', position: 8, country: 'BR'},
              {surname: 'Almeyda', position: 9, country: 'AZ'},
              {surname: 'Nadirov', position: 10, country: 'AZ'},
              {surname: 'Gelashvili', position: 11, country: 'GE'},
            ],
            substitutes: [
              {surname: 'Sattarli', position: 15, country: 'AZ'},
              {surname: 'George', position: 16, country: 'NL'},
              {surname: 'Kapolongo', position: 17, country: 'CG'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Szumski', position: 1, country: 'PL'},
              {surname: 'Klepczyński', position: 2, country: 'PL'},
              {surname: 'Horvath', position: 3, country: 'SK'},
              {surname: 'Polak', position: 4, country: 'CZ'},
              {surname: 'Zbozień', position: 5, country: 'PL'},
              {surname: 'Hanzel', position: 6, country: 'PL'},
              {surname: 'Matras', position: 7, country: 'PL'},
              {surname: 'Jurado', position: 8, country: 'ES'},
              {surname: 'Podgórski', position: 9, country: 'PL'},
              {surname: 'Izvolt', position: 10, country: 'SK'},
              {surname: 'Robak', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Murawski', position: 15, country: 'PL'},
              {surname: 'Cicman', position: 16, country: 'SK'},
              {surname: 'Wilczek', position: 17, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 10,
    question: 'Piast Gliwice 0-3 IFK Göteborg (14.07.2016) Eliminacje ligi Europy 2016/2017',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Piast Gliwice 0-3 IFK Göteborg (14.07.2016) Eliminacje ligi Europy 2016/2017',
          firstTeam: {
            formation: '1-3-5-2',
            footballers: [
              {surname: 'Jakub Szmatula', position: 1, country: 'PL'},
              {surname: 'Girdvainis', position: 2, country: 'LT'},
              {surname: 'Hebert', position: 3, country: 'BR'},
              {surname: 'Mokwa', position: 4, country: 'PL'},
              {surname: 'Pietrowski', position: 5, country: 'PL'},
              {surname: 'Murawski', position: 6, country: 'PL'},
              {surname: 'Bukata', position: 7, country: 'SK'},
              {surname: 'Mraz', position: 8, country: 'SK'},
              {surname: 'Szeliga', position: 9, country: 'PL'},
              {surname: 'Zivec', position: 10, country: 'SK'},
              {surname: 'Barisic', position: 11, country: 'HR'},
            ],
            substitutes: [
              {surname: 'Masłowski', position: 15, country: 'PL'},
              {surname: 'Jankowski', position: 16, country: 'PL'},
              {surname: 'Mak', position: 17, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Alvbåge', position: 1, country: 'SE'},
              {surname: 'Salomonsson', position: 2, country: 'SE'},
              {surname: 'Bjärsmyr', position: 3, country: 'SE'},
              {surname: 'Rogne', position: 4, country: 'NO'},
              {surname: 'Aleesami', position: 5, country: 'NO'},
              {surname: 'Rieks', position: 6, country: 'DK'},
              {surname: 'Albæk', position: 7, country: 'DK'},
              {surname: 'Eriksson', position: 8, country: 'SE'},
              {surname: 'Ankersen', position: 9, country: 'DK'},
              {surname: 'Boman', position: 10, country: 'SE'},
              {surname: 'Hysén', position: 11, country: 'SE'},
            ],
            substitutes: [
              {surname: 'Engvall', position: 15, country: 'SE'},
              {surname: 'Smedberg Dalence', position: 16, country: 'BO'},
              {surname: 'Pettersson', position: 17, country: 'SE'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 11,
    question: 'Piast Gliwice 1-0 Górnik Zabrze (03.04.2009) Ekstraklasa 2008/2009',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Piast Gliwice 1-0 Górnik Zabrze (03.04.2009) Ekstraklasa 2008/2009',
          firstTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Kasprzik', position: 1, country: 'PL'},
              {surname: 'Glik', position: 2, country: 'PL'},
              {surname: 'Kowalski', position: 3, country: 'PL'},
              {surname: 'Michniewicz', position: 4, country: 'PL'},
              {surname: 'Sedlacek', position: 5, country: 'CZ'},
              {surname: 'Muszalik', position: 6, country: 'PL'},
              {surname: 'Bojarski', position: 7, country: 'PL'},
              {surname: 'Kaszowski', position: 8, country: 'PL'},
              {surname: 'Podgorski', position: 9, country: 'PL'},
              {surname: 'Wilczek', position: 10, country: 'PL'},
              {surname: 'Olszar', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Chylaszek', position: 15, country: 'PL'},
              {surname: 'Koczon', position: 16, country: 'PL'},
              {surname: 'Smektała', position: 17, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-5-1',
            footballers: [
              {surname: 'Nowak', position: 1, country: 'PL'},
              {surname: 'Marciniak', position: 2, country: 'PL'},
              {surname: 'Pazdan', position: 3, country: 'PL'},
              {surname: 'Smirnovs', position: 4, country: 'LV'},
              {surname: 'Danch', position: 5, country: 'PL'},
              {surname: 'Strak', position: 6, country: 'PL'},
              {surname: 'Bonin', position: 7, country: 'PL'},
              {surname: 'Przybylski', position: 8, country: 'PL'},
              {surname: 'Szczot', position: 9, country: 'PL'},
              {surname: 'Gorawski', position: 10, country: 'PL'},
              {surname: 'Zahorski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Vaclavik', position: 15, country: 'CZ'},
              {surname: 'Jarka', position: 16, country: 'PL'},
              {surname: 'Kolodziej', position: 17, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 12,
    question: 'Śląsk Wrocław 1-1 Ruch Chorzów (18.02.2012) Ekstraklasa 2011/2012',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Śląsk Wrocław 1-1 Ruch Chorzów (18.02.2012) Ekstraklasa 2011/2012',
          firstTeam: {
            formation: '1-4-5-1',
            footballers: [
              {surname: 'Kelemen', position: 1, country: 'SK'},
              {surname: 'Celeban', position: 2, country: 'PL'},
              {surname: 'Pietrasiak', position: 3, country: 'PL'},
              {surname: 'Fojut', position: 4, country: 'PL'},
              {surname: 'Mraz', position: 5, country: 'SK'},
              {surname: 'Kazmierczak', position: 6, country: 'PL'},
              {surname: 'Elsner', position: 7, country: 'SI'},
              {surname: 'Mila', position: 8, country: 'PL'},
              {surname: 'Stevanovic', position: 9, country: 'SI'},
              {surname: 'Cetnarski', position: 10, country: 'PL'},
              {surname: 'Díaz', position: 11, country: 'AR'},
            ],
            substitutes: [
              {surname: 'Madej', position: 15, country: 'PL'},
              {surname: 'Cwielong', position: 16, country: 'PL'},
              {surname: 'Sztylka', position: 17, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-5-1',
            footballers: [
              {surname: 'Peskovic', position: 1, country: 'SK'},
              {surname: 'Grodzicki', position: 2, country: 'PL'},
              {surname: 'Stawarczyk', position: 3, country: 'PL'},
              {surname: 'Malinowski', position: 4, country: 'PL'},
              {surname: 'Burliga', position: 5, country: 'PL'},
              {surname: 'Djokic', position: 6, country: 'RS'},
              {surname: 'Straka', position: 7, country: 'SK'},
              {surname: 'Grzyb', position: 8, country: 'PL'},
              {surname: 'Janoszka', position: 9, country: 'PL'},
              {surname: 'Jankowski', position: 10, country: 'PL'},
              {surname: 'Piech', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Smektała', position: 15, country: 'PL'},
              {surname: 'Abbott', position: 16, country: 'PL'},
              {surname: 'Lisowski', position: 17, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 13,
    question: 'Jagiellonia Białystok2-2 Lech Poznań (04.06.2017) Ekstraklasa 2016/2017',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Jagiellonia Białystok 2-2 Lech Poznań (04.06.2017) Ekstraklasa 2016/2017',
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Kelemen', position: 1, country: 'SK'},
              {surname: 'Burliga', position: 2, country: 'PL'},
              {surname: 'Runje', position: 3, country: 'HR'},
              {surname: 'Guti', position: 4, country: 'ES'},
              {surname: 'Tomasik', position: 5, country: 'PL'},
              {surname: 'Goralski', position: 6, country: 'PL'},
              {surname: 'Romanchuk', position: 7, country: 'PL'},
              {surname: 'Frankowski', position: 8, country: 'PL'},
              {surname: 'Vassiljev', position: 9, country: 'EE'},
              {surname: 'Cernych', position: 10, country: 'LT'},
              {surname: 'Sheridan', position: 11, country: 'IE'},
            ],
            substitutes: [
              {surname: 'Świderski', position: 15, country: 'PL'},
              {surname: 'Novikovas', position: 16, country: 'LT'},
              {surname: 'Khomchenovskyi', position: 17, country: 'UA'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Putnocky', position: 1, country: 'SK'},
              {surname: 'Kędziora', position: 2, country: 'PL'},
              {surname: 'Bednarek', position: 3, country: 'PL'},
              {surname: 'Wilusz', position: 4, country: 'PL'},
              {surname: 'Kostevych', position: 5, country: 'UA'},
              {surname: 'Trałka', position: 6, country: 'PL'},
              {surname: 'Tetteh', position: 7, country: 'GH'},
              {surname: 'Makuszewski', position: 8, country: 'PL'},
              {surname: 'Jevtić', position: 9, country: 'CH'},
              {surname: 'Majewski', position: 10, country: 'PL'},
              {surname: 'Robak', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Pawlowski', position: 15, country: 'PL'},
              {surname: 'Bille', position: 16, country: 'DK'},
              {surname: 'Radut', position: 17, country: 'RO'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 14,
    question: 'Manchester City 0-1 Chelsea FC (29.05.2021) Finał LM 2020/2021',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Manchester City 0-1 Chelsea FC (29.05.2021) Finał LM 2020/2021',
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Ederson', position: 1, country: 'BR'},
              {surname: 'Walker', position: 2, country: 'EN'},
              {surname: 'Stones', position: 3, country: 'EN'},
              {surname: 'Dias', position: 4, country: 'PT'},
              {surname: 'Zinchenko', position: 5, country: 'UA'},
              {surname: 'Gündogan', position: 6, country: 'DE'},
              {surname: 'Bernardo Silva', position: 7, country: 'PT'},
              {surname: 'Foden', position: 8, country: 'EN'},
              {surname: 'De Bruyne', position: 9, country: 'BE'},
              {surname: 'Mahrez', position: 10, country: 'DZ'},
              {surname: 'Sterling', position: 11, country: 'EN'},
            ],
            substitutes: [
              {surname: 'Gabriel Jesus', position: 15, country: 'BR'},
              {surname: 'Fernandinho', position: 16, country: 'BR'},
              {surname: 'Agüero', position: 17, country: 'AR'},
            ],
          },
          secondTeam: {
            formation: '1-3-4-2-1',
            footballers: [
              {surname: 'Mendy', position: 1, country: 'SN'},
              {surname: 'Azpilicueta', position: 2, country: 'ES'},
              {surname: 'Thiago Silva', position: 3, country: 'BR'},
              {surname: 'Rüdiger', position: 4, country: 'DE'},
              {surname: 'James', position: 5, country: 'EN'},
              {surname: 'Jorginho', position: 6, country: 'IT'},
              {surname: 'Kanté', position: 7, country: 'FR'},
              {surname: 'Chilwell', position: 8, country: 'EN'},
              {surname: 'Mount', position: 9, country: 'EN'},
              {surname: 'Werner', position: 10, country: 'DE'},
              {surname: 'Havertz', position: 11, country: 'DE'},
            ],
            substitutes: [
              {surname: 'Christensen', position: 15, country: 'DK'},
              {surname: 'Pulisic', position: 16, country: 'US'},
              {surname: 'Kovačić', position: 17, country: 'HR'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 15,
    question: 'SSC Napoli 5-1 Juventus FC  (13.01.2023) Serie A 2022/2023',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'SSC Napoli 5-1 Juventus FC  (13.01.2023) Serie A 2022/2023',
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Meret', position: 1, country: 'IT'},
              {surname: 'Mario Rui', position: 2, country: 'PT'},
              {surname: 'Kim', position: 3, country: 'KR'},
              {surname: 'Rrahmani', position: 4, country: 'XK'},
              {surname: ' Di Lorenzo', position: 5, country: 'IT'},
              {surname: ' Lobotka', position: 6, country: 'SK'},
              {surname: 'Anguissa', position: 7, country: 'CM'},
              {surname: 'Zieliński', position: 8, country: 'PL'},
              {surname: 'Kvaratskhelia', position: 9, country: 'GE'},
              {surname: 'Osimhen', position: 10, country: 'NG'},
              {surname: 'Politano', position: 11, country: 'IT'},
            ],
            substitutes: [
              {surname: 'Olivera', position: 15, country: 'UY'},
              {surname: 'Ndombélé', position: 16, country: 'FR'},
              {surname: 'Elmas', position: 17, country: 'MK'},
              {surname: 'Lozano', position: 18, country: 'MX'},
              {surname: 'Raspadori', position: 19, country: 'IT'},
            ],
          },
          secondTeam: {
            formation: '1-3-5-2',
            footballers: [
              {surname: 'Szczęsny', position: 1, country: 'PL'},
              {surname: 'Danilo', position: 2, country: 'BR'},
              {surname: 'Bremer', position: 3, country: 'BR'},
              {surname: 'Sandro', position: 4, country: 'BR'},
              {surname: 'Kostić', position: 5, country: 'RS'},
              {surname: 'Locatelli', position: 6, country: 'IT'},
              {surname: 'Rabiot', position: 7, country: 'FR'},
              {surname: 'McKennie', position: 8, country: 'US'},
              {surname: 'Chiesa', position: 9, country: 'IT'},
              {surname: 'Milik', position: 10, country: 'PL'},
              {surname: 'Di María', position: 11, country: 'AR'},
            ],
            substitutes: [
              {surname: 'Iling-Junior', position: 15, country: 'EN'},
              {surname: 'Paredes', position: 16, country: 'AR'},
              {surname: 'Miretti', position: 17, country: 'IT'},
              {surname: 'Soulé', position: 18, country: 'AR'},
              {surname: 'Kean', position: 19, country: 'IT'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 16,
    question: 'Totenham Hotspur 0-2 Arsenal FC (15.01.2023 )Premier League 2022/2023',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Totenham Hotspur 0-2 Arsenal FC (15.01.2023 )Premier League 2022/2023',
          firstTeam: {
            formation: '1-3-4-3',
            footballers: [
              {surname: 'Lloris', position: 1, country: 'FR'},
              {surname: 'Romero', position: 2, country: 'AR'},
              {surname: 'Dier', position: 3, country: 'EN'},
              {surname: 'Lenglet', position: 4, country: 'FR'},
              {surname: 'Doherty', position: 5, country: 'IE'},
              {surname: 'Højbjerg', position: 6, country: 'DK'},
              {surname: 'Sarr', position: 7, country: 'SN'},
              {surname: 'Sessegnon', position: 8, country: 'EN'},
              {surname: 'Kulusevski', position: 9, country: 'SE'},
              {surname: 'Son', position: 10, country: 'KR'},
              {surname: 'Kane', position: 11, country: 'EN'},
            ],
            substitutes: [
              {surname: 'Richarlison', position: 12, country: 'BR'},
              {surname: 'Bissouma', position: 13, country: 'ML'},
              {surname: 'Perišić', position: 14, country: 'HR'},
              {surname: 'Gil', position: 15, country: 'ES'},
              {surname: 'Davies', position: 16, country: 'EN'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Ramsdale', position: 1, country: 'EN'},
              {surname: 'White', position: 2, country: 'EN'},
              {surname: 'Saliba', position: 3, country: 'FR'},
              {surname: 'Gabriel', position: 4, country: 'BR'},
              {surname: 'Zinchenko', position: 5, country: 'UA'},
              {surname: 'Partey', position: 6, country: 'GH'},
              {surname: 'Xhaka', position: 7, country: 'CH'},
              {surname: 'Ødegaard', position: 8, country: 'NO'},
              {surname: 'Saka', position: 9, country: 'EN'},
              {surname: 'Martinelli', position: 10, country: 'BR'},
              {surname: 'Nketiah', position: 11, country: 'EN'},
            ],
            substitutes: [
              {surname: 'Tierney', position: 12, country: 'EN'},
              {surname: 'Tomiyasu', position: 13, country: 'JP'},
              {surname: 'Vieira', position: 14, country: 'PT'},
              {surname: 'Rowe', position: 15, country: 'EN'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 17,
    question: 'Piast Gliwice vs Bruk-Bet Termalica Nieciecza (19.05.2018) Ekstraklasa 2017/2018',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: '',
        football: {
          name: 'Piast Gliwice vs Bruk-Bet Termalica Nieciecza (19.05.2018) Ekstraklasa 2017/2018',
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Szmatuła', position: 1, country: 'PL'},
              {surname: 'Konczkowski', position: 2, country: 'PL'},
              {surname: 'Sedlar', position: 3, country: 'RS'},
              {surname: 'Czerwiński', position: 4, country: 'PL'},
              {surname: 'Pietrowski', position: 5, country: 'PL'},
              {surname: 'Dziczek', position: 6, country: 'PL'},
              {surname: 'Jodłowiec', position: 7, country: 'PL'},
              {surname: 'Mak', position: 8, country: 'PL'},
              {surname: 'Bukata', position: 9, country: 'SK'},
              {surname: 'Živec', position: 10, country: 'SI'},
              {surname: 'Papadopulos', position: 11, country: 'CZ'},
            ],
            substitutes: [
              {surname: 'Angielski', position: 15, country: 'PL'},
              {surname: 'Badia', position: 16, country: 'ES'},
              {surname: 'Gojko', position: 17, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Trela', position: 1, country: 'PL'},
              {surname: 'Szeliga', position: 2, country: 'PL'},
              {surname: 'Kupczak', position: 3, country: 'PL'},
              {surname: 'Putivtsev', position: 4, country: 'UA'},
              {surname: 'Maksimenko', position: 5, country: 'LV'},
              {surname: 'Jovanović', position: 6, country: 'RS'},
              {surname: 'Grzelak', position: 7, country: 'PL'},
              {surname: 'Śpiączka', position: 8, country: 'PL'},
              {surname: 'Purece', position: 9, country: 'RO'},
              {surname: 'Pawlowski', position: 10, country: 'PL'},
              {surname: 'Gutkovskis', position: 11, country: 'LV'},
            ],
            substitutes: [
              {surname: 'Piątek', position: 15, country: 'PL'},
              {surname: 'Štefánik', position: 16, country: 'SK'},
              {surname: 'Gergel', position: 17, country: 'SK'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 18,
    question: 'Argentyna 3-3 (k. 4-2) Francja (18.12.2022) Finał Mundialu 2022',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Argentyna - Francja',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Martínez', position: 1, country: 'AR'},
              {surname: 'Tagliafico', position: 2, country: 'AR'},
              {surname: 'Otamendi', position: 3, country: 'AR'},
              {surname: 'Romero', position: 4, country: 'AR'},
              {surname: 'Molina', position: 5, country: 'AR'},
              {surname: 'Mac Allister', position: 6, country: 'AR'},
              {surname: 'Fernández', position: 7, country: 'AR'},
              {surname: 'De Paul', position: 8, country: 'AR'},
              {surname: 'Álvarez', position: 9, country: 'AR'},
              {surname: 'Messi', position: 10, country: 'AR'},
              {surname: 'Di María', position: 11, country: 'AR'},
            ],
            substitutes: [
              {surname: 'Acuña', position: 15, country: 'AR'},
              {surname: 'Montiel', position: 16, country: 'AR'},
              {surname: 'Paredes', position: 17, country: 'AR'},
              {surname: 'Lautaro', position: 18, country: 'AR'},
              {surname: 'Pezzella', position: 19, country: 'AR'},
              {surname: 'Dybala', position: 20, country: 'AR'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Lloris', position: 1, country: 'FR'},
              {surname: 'Hernández', position: 2, country: 'FR'},
              {surname: 'Upamecano', position: 3, country: 'FR'},
              {surname: 'Varane', position: 4, country: 'FR'},
              {surname: 'Koundé', position: 5, country: 'FR'},
              {surname: 'Tchouaméni', position: 6, country: 'FR'},
              {surname: 'Rabiot', position: 7, country: 'FR'},
              {surname: 'Griezmann', position: 8, country: 'FR'},
              {surname: 'Mbappé', position: 9, country: 'FR'},
              {surname: 'Giroud', position: 10, country: 'FR'},
              {surname: 'Dembélé', position: 11, country: 'FR'},
            ],
            substitutes: [
              {surname: 'Kolo Muani', position: 15, country: 'FR'},
              {surname: 'Thuram', position: 16, country: 'FR'},
              {surname: 'Coman', position: 17, country: 'FR'},
              {surname: 'Camavinga', position: 18, country: 'FR'},
              {surname: 'Fofana', position: 19, country: 'FR'},
              {surname: 'Konaté', position: 20, country: 'FR'},
              {surname: 'Disasi', position: 21, country: 'FR'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 19,
    question: 'Liverpool FC 4-0 FC Barcelona (07.05.2019) Półfinał Ligi Mistrzów 2018/2019',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Liverpool - Barcelona',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Alisson', position: 1, country: 'BR'},
              {surname: 'Robertson', position: 2, country: 'SCT'},
              {surname: 'van Dijk', position: 3, country: 'NL'},
              {surname: 'Matip', position: 4, country: 'CM'},
              {surname: 'Alexander-Arnold', position: 5, country: 'EN'},
              {surname: 'Fabinho', position: 6, country: 'BR'},
              {surname: 'Milner', position: 7, country: 'EN'},
              {surname: 'Henderson', position: 8, country: 'EN'},
              {surname: 'Mané', position: 9, country: 'SN'},
              {surname: 'Origi', position: 10, country: 'BE'},
              {surname: 'Shaqiri', position: 11, country: 'CH'},
            ],
            substitutes: [
              {surname: 'Wijnaldum', position: 15, country: 'NL'}, // wszedł za Robertsona (kontuzja) i strzelił 2 gole
              {surname: 'Gomez', position: 16, country: 'EN'},
              {surname: 'Sturridge', position: 17, country: 'EN'},
            ],
          },
          secondTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'ter Stegen', position: 1, country: 'DE'},
              {surname: 'Alba', position: 2, country: 'ES'},
              {surname: 'Lenglet', position: 3, country: 'FR'},
              {surname: 'Piqué', position: 4, country: 'ES'},
              {surname: 'Roberto', position: 5, country: 'ES'},
              {surname: 'Busquets', position: 6, country: 'ES'},
              {surname: 'Rakitić', position: 7, country: 'HR'},
              {surname: 'Vidal', position: 8, country: 'CL'},
              {surname: 'Coutinho', position: 9, country: 'BR'},
              {surname: 'Suárez', position: 10, country: 'UY'},
              {surname: 'Messi', position: 11, country: 'AR'},
            ],
            substitutes: [
              {surname: 'Semedo', position: 15, country: 'PT'},
              {surname: 'Melo', position: 16, country: 'BR'},
              {surname: 'Malcom', position: 17, country: 'BR'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 20,
    question: ' Liverpool FC 4-3 Borussia Dortmund (14.04.2016) Ćwierćfinał Ligi Europy 2015/2016',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Liverpool - Borussia Dortmund',
        football: {
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Mignolet', position: 1, country: 'BE'},
              {surname: 'Moreno', position: 2, country: 'ES'},
              {surname: 'Sakho', position: 3, country: 'FR'},
              {surname: 'Lovren', position: 4, country: 'HR'},
              {surname: 'Clyne', position: 5, country: 'EN'},
              {surname: 'Can', position: 6, country: 'DE'},
              {surname: 'Milner', position: 7, country: 'EN'},
              {surname: 'Coutinho', position: 8, country: 'BR'},
              {surname: 'Firmino', position: 9, country: 'BR'},
              {surname: 'Lallana', position: 10, country: 'EN'},
              {surname: 'Origi', position: 11, country: 'BE'},
            ],
            substitutes: [
              {surname: 'Allen', position: 15, country: 'WLS'},
              {surname: 'Sturridge', position: 16, country: 'EN'},
              {surname: 'Lucas Leiva', position: 17, country: 'BR'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Weidenfeller', position: 1, country: 'DE'},
              {surname: 'Schmelzer', position: 2, country: 'DE'},
              {surname: 'Hummels', position: 3, country: 'DE'},
              {surname: 'Sokratis', position: 4, country: 'GR'},
              {surname: 'Piszczek', position: 5, country: 'PL'},
              {surname: 'Weigl', position: 6, country: 'DE'},
              {surname: 'Castro', position: 7, country: 'DE'},
              {surname: 'Reus', position: 8, country: 'DE'},
              {surname: 'Kagawa', position: 9, country: 'JP'},
              {surname: 'Mkhitaryan', position: 10, country: 'AM'},
              {surname: 'Aubameyang', position: 11, country: 'GA'},
            ],
            substitutes: [
              {surname: 'Ginter', position: 15, country: 'DE'},
              {surname: 'Gündoğan', position: 16, country: 'DE'},
              {surname: 'Ramos', position: 17, country: 'CO'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 21,
    question: 'Polska 2-0 Niemcy (11.10.2014) Eliminacje Mistrzostw Europy 2016',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Polska - Niemcy',
        football: {
          firstTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Szczęsny', position: 1, country: 'PL'},
              {surname: 'Wawrzyniak', position: 2, country: 'PL'},
              {surname: 'Szukała', position: 3, country: 'PL'},
              {surname: 'Glik', position: 4, country: 'PL'},
              {surname: 'Piszczek', position: 5, country: 'PL'},
              {surname: 'Grosicki', position: 6, country: 'PL'},
              {surname: 'Krychowiak', position: 7, country: 'PL'},
              {surname: 'Jodłowiec', position: 8, country: 'PL'},
              {surname: 'Rybus', position: 9, country: 'PL'},
              {surname: 'Milik', position: 10, country: 'PL'},
              {surname: 'Lewandowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Sobota', position: 15, country: 'PL'},
              {surname: 'Mila', position: 16, country: 'PL'}, // Strzelec bramki na 2-0
              {surname: 'Jedrzejczyk', position: 17, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Neuer', position: 1, country: 'DE'},
              {surname: 'Durm', position: 2, country: 'DE'},
              {surname: 'Hummels', position: 3, country: 'DE'},
              {surname: 'Boateng', position: 4, country: 'DE'},
              {surname: 'Rüdiger', position: 5, country: 'DE'},
              {surname: 'Kroos', position: 6, country: 'DE'},
              {surname: 'Kramer', position: 7, country: 'DE'},
              {surname: 'Schürrle', position: 8, country: 'DE'},
              {surname: 'Götze', position: 9, country: 'DE'},
              {surname: 'Bellarabi', position: 10, country: 'DE'},
              {surname: 'Müller', position: 11, country: 'DE'},
            ],
            substitutes: [
              {surname: 'Podolski', position: 15, country: 'DE'},
              {surname: 'Draxler', position: 16, country: 'DE'},
              {surname: 'Kruse', position: 17, country: 'DE'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 22,
    question: 'Piast Gliwice 3-0 Zawisza Bydgoszcz (27.05.2012) I Liga 2011/2012',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Piast Gliwice - Zawisza Bydgoszcz',
        football: {
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Trela', position: 1, country: 'PL'},
              {surname: 'Bodzioch', position: 2, country: 'PL'},
              {surname: 'Krzycki', position: 3, country: 'PL'},
              {surname: 'Klepczyński', position: 4, country: 'PL'},
              {surname: 'Matras', position: 5, country: 'PL'},
              {surname: 'Jurado', position: 6, country: 'ES'},
              {surname: 'Zganiacz', position: 7, country: 'PL'},
              {surname: 'Podgórski', position: 8, country: 'PL'},
              {surname: 'Jurado', position: 9, country: 'ES'},
              {surname: 'Cicman', position: 10, country: 'SK'},
              {surname: 'Kędziora', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Dočekal', position: 12, country: 'CZ'},
              {surname: 'Buryán', position: 13, country: 'CZ'},
            ],
          },
          secondTeam: {
            formation: '1-4-5-1',
            footballers: [
              {surname: 'Witan', position: 1, country: 'PL'},
              {surname: 'Oleksy', position: 2, country: 'PL'},
              {surname: 'Skrzyński', position: 3, country: 'PL'},
              {surname: 'Dryzmont', position: 4, country: 'PL'},
              {surname: 'Stefańczyk', position: 5, country: 'PL'},
              {surname: 'Ekwueme', position: 6, country: 'NG'},
              {surname: 'Zawistowski', position: 7, country: 'PL'},
              {surname: 'Błąd', position: 8, country: 'PL'},
              {surname: 'Wójcicki', position: 9, country: 'PL'},
              {surname: 'Stark', position: 10, country: 'PL'},
              {surname: 'Leśniewski', position: 11, country: 'PL'}
            ],
            substitutes: [
              {surname: 'Gevorgyan', position: 16, country: 'AM'},
              {surname: 'Masłowski', position: 17, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 23,
    question: 'Anglia 1-2 Islandia (27.06.2016) 1/8 finału Mistrzostw Europy 2016',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Anglia - Islandia',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Hart', position: 1, country: 'ENG'},
              {surname: 'Rose', position: 2, country: 'ENG'},
              {surname: 'Smalling', position: 3, country: 'ENG'},
              {surname: 'Cahill', position: 4, country: 'ENG'},
              {surname: 'Walker', position: 5, country: 'ENG'},
              {surname: 'Rooney', position: 6, country: 'ENG'},
              {surname: 'Dier', position: 7, country: 'ENG'},
              {surname: 'Alli', position: 8, country: 'ENG'},
              {surname: 'Sterling', position: 9, country: 'ENG'},
              {surname: 'Kane', position: 10, country: 'ENG'},
              {surname: 'Sturridge', position: 11, country: 'ENG'},
            ],
            substitutes: [
              {surname: 'Wilshere', position: 15, country: 'ENG'},
              {surname: 'Vardy', position: 16, country: 'ENG'},
              {surname: 'Rashford', position: 17, country: 'ENG'},
            ],
          },
          secondTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Halldorsson', position: 1, country: 'IS'},
              {surname: 'Skulason', position: 2, country: 'IS'},
              {surname: 'Sigurdsson', position: 3, country: 'IS'}, // Strzelec bramki na 1-1
              {surname: 'Árnason', position: 4, country: 'IS'},
              {surname: 'Sevarsson', position: 5, country: 'IS'},
              {surname: 'Bjarnason', position: 6, country: 'IS'},
              {surname: 'Sigurðsson', position: 7, country: 'IS'},
              {surname: 'Gunnarsson', position: 8, country: 'IS'},
              {surname: 'Gudmundsson', position: 9, country: 'IS'},
              {surname: 'Bovarsson', position: 10, country: 'IS'},
              {surname: 'Sigþorsson', position: 11, country: 'IS'}, // Strzelec bramki na 1-2
            ],
            substitutes: [
              {surname: 'Bjarnason', position: 15, country: 'IS'},
              {surname: 'Traustason', position: 16, country: 'IS'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 24,
    question: 'Polska 1-1 (k. 3-5) Portugalia (30.06.2016) Ćwierćfinał Mistrzostw Europy 2016',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Polska - Portugalia',
        football: {
          firstTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Fabiański', position: 1, country: 'PL'},
              {surname: 'Jędrzejczyk', position: 2, country: 'PL'},
              {surname: 'Pazdan', position: 3, country: 'PL'},
              {surname: 'Glik', position: 4, country: 'PL'},
              {surname: 'Piszczek', position: 5, country: 'PL'},
              {surname: 'Grosicki', position: 6, country: 'PL'},
              {surname: 'Mączyński', position: 7, country: 'PL'},
              {surname: 'Krychowiak', position: 8, country: 'PL'},
              {surname: 'Błaszczykowski', position: 9, country: 'PL'},
              {surname: 'Milik', position: 10, country: 'PL'},
              {surname: 'Lewandowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Kapustka', position: 15, country: 'PL'},
              {surname: 'Jodłowiec', position: 16, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-1-3-2',
            footballers: [
              {surname: 'Patrício', position: 1, country: 'PT'},
              {surname: 'Eliseu', position: 2, country: 'PT'},
              {surname: 'Fonte', position: 3, country: 'PT'},
              {surname: 'Pepe', position: 4, country: 'PT'},
              {surname: 'Soraes', position: 5, country: 'PT'},
              {surname: 'Silva', position: 6, country: 'PT'},
              {surname: 'Carvalho', position: 7, country: 'PT'},
              {surname: 'Sanches', position: 8, country: 'PT'},
              {surname: 'João Mário', position: 9, country: 'PT'},
              {surname: 'Nani', position: 10, country: 'PT'},
              {surname: 'Ronaldo', position: 11, country: 'PT'},
            ],
            substitutes: [
              {surname: 'Moutinho', position: 15, country: 'PT'},
              {surname: 'Quaresma', position: 16, country: 'PT'},
              {surname: 'Pereira', position: 17, country: 'PT'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 25,
    question: 'Borussia Dortmund 5-2 Bayern Monachium (12.05.2012) Finał DFB Pokal 2011/2012',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Borussia Dortmund - Bayern Monachium',
        football: {
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Weidenfeller', position: 1, country: 'DE'},
              {surname: 'Schmelzer', position: 2, country: 'DE'},
              {surname: 'Hummels', position: 3, country: 'DE'},
              {surname: 'Subotić', position: 4, country: 'RS'},
              {surname: 'Piszczek', position: 5, country: 'PL'},
              {surname: 'Kehl', position: 6, country: 'DE'},
              {surname: 'Gündoğan', position: 7, country: 'DE'},
              {surname: 'Großkreutz', position: 8, country: 'DE'},
              {surname: 'Kagawa', position: 9, country: 'JP'},
              {surname: 'Błaszczykowski', position: 10, country: 'PL'},
              {surname: 'Lewandowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Langerak', position: 15, country: 'AU'}, // wszedł za kontuzjowanego Weidenfellera
              {surname: 'Bender', position: 16, country: 'DE'},
              {surname: 'Perišić', position: 17, country: 'HR'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Neuer', position: 1, country: 'DE'},
              {surname: 'Alaba', position: 2, country: 'AT'},
              {surname: 'Badstuber', position: 3, country: 'DE'},
              {surname: 'Boateng', position: 4, country: 'DE'},
              {surname: 'Lahm', position: 5, country: 'DE'},
              {surname: 'Schweinsteiger', position: 6, country: 'DE'},
              {surname: 'Luiz Gustavo', position: 7, country: 'BR'},
              {surname: 'Ribéry', position: 8, country: 'FR'},
              {surname: 'Kroos', position: 9, country: 'DE'},
              {surname: 'Robben', position: 10, country: 'NL'},
              {surname: 'Gómez', position: 11, country: 'DE'},
            ],
            substitutes: [
              {surname: 'Müller', position: 15, country: 'DE'},
              {surname: 'Contento', position: 16, country: 'DE'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 26,
    question: 'Borussia Dortmund 1-2 Bayern Monachium (25.05.2013) Finał Ligi Mistrzów 2012/2013',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Borussia Dortmund - Bayern Monachium',
        football: {
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Weidenfeller', position: 1, country: 'DE'},
              {surname: 'Schmelzer', position: 2, country: 'DE'},
              {surname: 'Hummels', position: 3, country: 'DE'},
              {surname: 'Subotić', position: 4, country: 'RS'},
              {surname: 'Piszczek', position: 5, country: 'PL'},
              {surname: 'Bender', position: 6, country: 'DE'},
              {surname: 'Gündoğan', position: 7, country: 'DE'},
              {surname: 'Großkreutz', position: 8, country: 'DE'},
              {surname: 'Reus', position: 9, country: 'DE'},
              {surname: 'Błaszczykowski', position: 10, country: 'PL'},
              {surname: 'Lewandowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Sahin', position: 15, country: 'TR'},
              {surname: 'Schieber', position: 16, country: 'DE'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Neuer', position: 1, country: 'DE'},
              {surname: 'Alaba', position: 2, country: 'AT'},
              {surname: 'Dante', position: 3, country: 'BR'},
              {surname: 'Boateng', position: 4, country: 'DE'},
              {surname: 'Lahm', position: 5, country: 'DE'},
              {surname: 'Schweinsteiger', position: 6, country: 'DE'},
              {surname: 'Javi Martínez', position: 7, country: 'ES'},
              {surname: 'Ribéry', position: 8, country: 'FR'},
              {surname: 'Müller', position: 9, country: 'DE'},
              {surname: 'Robben', position: 10, country: 'NL'},
              {surname: 'Mandžukić', position: 11, country: 'HR'},
            ],
            substitutes: [
              {surname: 'Gustavo', position: 15, country: 'BR'},
              {surname: 'Gomez', position: 16, country: 'DE'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 27,
    question: 'Borussia Dortmund 4-1 Real Madryt (24.04.2013) Półfinał Ligi Mistrzów 2012/2013',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Borussia Dortmund - Real Madryt',
        football: {
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Weidenfeller', position: 1, country: 'DE'},
              {surname: 'Schmelzer', position: 2, country: 'DE'},
              {surname: 'Hummels', position: 3, country: 'DE'},
              {surname: 'Subotić', position: 4, country: 'RS'},
              {surname: 'Piszczek', position: 5, country: 'PL'},
              {surname: 'Bender', position: 6, country: 'DE'},
              {surname: 'Gündoğan', position: 7, country: 'DE'},
              {surname: 'Reus', position: 8, country: 'DE'},
              {surname: 'Götze', position: 9, country: 'DE'},
              {surname: 'Błaszczykowski', position: 10, country: 'PL'},
              {surname: 'Lewandowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Kehl', position: 15, country: 'DE'},
              {surname: 'Großkreutz', position: 16, country: 'DE'},
              {surname: 'Schieber', position: 17, country: 'DE'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Diego López', position: 1, country: 'ES'},
              {surname: 'Coentrão', position: 2, country: 'PT'},
              {surname: 'Pepe', position: 3, country: 'PT'},
              {surname: 'Varane', position: 4, country: 'FR'},
              {surname: 'Ramos', position: 5, country: 'ES'},
              {surname: 'Alonso', position: 6, country: 'ES'},
              {surname: 'Khedira', position: 7, country: 'DE'},
              {surname: 'Ronaldo', position: 8, country: 'PT'},
              {surname: 'Özil', position: 9, country: 'DE'},
              {surname: 'Modrić', position: 10, country: 'HR'},
              {surname: 'Higuaín', position: 11, country: 'AR'},
            ],
            substitutes: [
              {surname: 'Di María', position: 15, country: 'AR'},
              {surname: 'Benzema', position: 16, country: 'FR'},
              {surname: 'Kaka', position: 17, country: 'BR'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 28,
    question: 'Piast Gliwice 2-1 Jagiellonia Białystok (12.05.2019) Ekstraklasa 2018/2019',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Piast Gliwice - Jagiellonia Białystok',
        football: {
          firstTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Szmatuła', position: 1, country: 'SK'},
              {surname: 'Kirkeskov', position: 2, country: 'DK'},
              {surname: 'Czerwiński', position: 3, country: 'PL'},
              {surname: 'Sedlar', position: 4, country: 'RS'},
              {surname: 'Pietrowski', position: 5, country: 'PL'},
              {surname: 'Jodłowiec', position: 6, country: 'PL'},
              {surname: 'Dziczek', position: 7, country: 'PL'},
              {surname: 'Valencia', position: 8, country: 'EC'},
              {surname: 'Badia', position: 9, country: 'ES'},
              {surname: 'Konczkowski', position: 10, country: 'PL'},
              {surname: 'Parzyszek', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Felix', position: 15, country: 'ES'},
              {surname: 'Sokołowski', position: 16, country: 'PL'},
              {surname: 'Papadopulos', position: 17, country: 'CZ'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Sandomierski', position: 1, country: 'PL'},
              {surname: 'Böðvarsson', position: 2, country: 'IS'},
              {surname: 'Runje', position: 3, country: 'HR'},
              {surname: 'Arsenić', position: 4, country: 'HR'},
              {surname: 'Kadlec', position: 5, country: 'CZ'},
              {surname: 'Adamec', position: 6, country: 'SK'},
              {surname: 'Poletanović', position: 7, country: 'RS'},
              {surname: 'Pospisil', position: 8, country: 'CZ'},
              {surname: 'Imaz', position: 9, country: 'ES'},
              {surname: 'Novikovas', position: 10, country: 'LT'},
              {surname: 'Wójcicki', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Guilherme', position: 15, country: 'BR'},
              {surname: 'Romanczuk', position: 16, country: 'PL'},
              {surname: 'Kostal', position: 17, country: 'SK'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 29,
    question: 'Włochy 1-1 (k. 5-3) Francja (09.07.2006) Finał Mistrzostw Świata 2006',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Włochy - Francja',
        football: {
          firstTeam: {
            formation: '1-4-4-1-1',
            footballers: [
              {surname: 'Buffon', position: 1, country: 'IT'},
              {surname: 'Grosso', position: 2, country: 'IT'},
              {surname: 'Cannavaro', position: 3, country: 'IT'},
              {surname: 'Materazzi', position: 4, country: 'IT'},
              {surname: 'Zambrotta', position: 5, country: 'IT'},
              {surname: 'Perrotta', position: 6, country: 'IT'},
              {surname: 'Pirlo', position: 7, country: 'IT'},
              {surname: 'Gattuso', position: 8, country: 'IT'},
              {surname: 'Camoranesi', position: 9, country: 'IT'},
              {surname: 'Totti', position: 10, country: 'IT'},
              {surname: 'Toni', position: 11, country: 'IT'},
            ],
            substitutes: [
              {surname: 'De Rossi', position: 15, country: 'IT'},
              {surname: 'Iaquinta', position: 16, country: 'IT'},
              {surname: 'Del Piero', position: 17, country: 'IT'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Barthez', position: 1, country: 'FR'},
              {surname: 'Abidal', position: 2, country: 'FR'},
              {surname: 'Gallas', position: 3, country: 'FR'},
              {surname: 'Thuram', position: 4, country: 'FR'},
              {surname: 'Sagnol', position: 5, country: 'FR'},
              {surname: 'Makelele', position: 6, country: 'FR'},
              {surname: 'Vieira', position: 7, country: 'FR'},
              {surname: 'Malouda', position: 8, country: 'FR'},
              {surname: 'Zidane', position: 9, country: 'FR'},
              {surname: 'Ribéry', position: 10, country: 'FR'},
              {surname: 'Henry', position: 11, country: 'FR'},
            ],
            substitutes: [
              {surname: 'Diarra', position: 15, country: 'FR'},
              {surname: 'Trezeguet', position: 16, country: 'FR'}, // Jedyny, który nie trafił karnego
              {surname: 'Wiltord', position: 17, country: 'FR'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 30,
    question: 'Polska 2-0 Szwecja (29.03.2022) Finał baraży o Mistrzostwa Świata 2022',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Polska - Szwecja',
        football: {
          firstTeam: {
            formation: '1-4-1-4-1',
            footballers: [
              {surname: 'Szczęsny', position: 1, country: 'PL'},
              {surname: 'Bereszyński', position: 2, country: 'PL'},
              {surname: 'Bednarek', position: 3, country: 'PL'},
              {surname: 'Glik', position: 4, country: 'PL'},
              {surname: 'Cash', position: 5, country: 'PL'},
              {surname: 'Bielik', position: 6, country: 'PL'},
              {surname: 'Szymański', position: 7, country: 'PL'},
              {surname: 'Moder', position: 8, country: 'PL'},
              {surname: 'Góralski', position: 9, country: 'PL'},
              {surname: 'Zieliński', position: 10, country: 'PL'},
              {surname: 'Lewandowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Krychowiak', position: 15, country: 'PL'}, // Wywalczył rzut karny
              {surname: 'Buksa', position: 16, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Olsen', position: 1, country: 'SE'},
              {surname: 'Augustinsson', position: 2, country: 'SE'},
              {surname: 'Danielson', position: 3, country: 'SE'},
              {surname: 'Lindelöf', position: 4, country: 'SE'},
              {surname: 'Krafth', position: 5, country: 'SE'},
              {surname: 'Forsberg', position: 6, country: 'SE'},
              {surname: 'Olsson', position: 7, country: 'SE'},
              {surname: 'Karlström', position: 8, country: 'SE'},
              {surname: 'Kulusevski', position: 9, country: 'SE'},
              {surname: 'Isak', position: 10, country: 'SE'},
              {surname: 'Quaison', position: 11, country: 'SE'},
            ],
            substitutes: [
              {surname: 'Ibrahimović', position: 15, country: 'SE'},
              {surname: 'Elanga', position: 16, country: 'SE'},
              {surname: 'Svanberg', position: 17, country: 'SE'},
              {surname: 'Karlsson', position: 18, country: 'SE'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 31,
    question: 'Francja 1-1 Polska (25.06.2024) Faza Grupowa Mistrzostw Europy 2024',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Francja - Polska',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Maignan', position: 1, country: 'FR'},
              {surname: 'Hernández', position: 2, country: 'FR'},
              {surname: 'Saliba', position: 3, country: 'FR'},
              {surname: 'Upamecano', position: 4, country: 'FR'},
              {surname: 'Koundé', position: 5, country: 'FR'},
              {surname: 'Rabiot', position: 6, country: 'FR'},
              {surname: 'Tchouaméni', position: 7, country: 'FR'},
              {surname: 'Kanté', position: 8, country: 'FR'},
              {surname: 'Barcola', position: 9, country: 'FR'},
              {surname: 'Mbappé', position: 10, country: 'FR'},
              {surname: 'Dembélé', position: 11, country: 'FR'},
            ],
            substitutes: [
              {surname: 'Camavinga', position: 15, country: 'FR'},
              {surname: 'Griezmann', position: 16, country: 'FR'},
              {surname: 'Giroud', position: 17, country: 'FR'},
              {surname: 'Kolo Muani', position: 18, country: 'FR'},
              {surname: 'Fofana', position: 19, country: 'FR'},
            ],
          },
          secondTeam: {
            formation: '1-5-3-2',
            footballers: [
              {surname: 'Skorupski', position: 1, country: 'PL'},
              {surname: 'Kiwior', position: 2, country: 'PL'},
              {surname: 'Dawidowicz', position: 3, country: 'PL'},
              {surname: 'Bednarek', position: 4, country: 'PL'},
              {surname: 'Zalewski', position: 5, country: 'PL'},
              {surname: 'Moder', position: 6, country: 'PL'},
              {surname: 'Zieliński', position: 7, country: 'PL'},
              {surname: 'Frankowski', position: 8, country: 'PL'},
              {surname: 'Szymański', position: 9, country: 'PL'},
              {surname: 'Urbański', position: 10, country: 'PL'},
              {surname: 'Lewandowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Świderski', position: 15, country: 'PL'}, // Wywalczył rzut karny
              {surname: 'Skóraś', position: 16, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 32,
    question: 'Hiszpania 1-1 Polska (19.06.2021) Faza grupowa Mistrzostw Europy 2020',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Hiszpania - Polska',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Simon', position: 1, country: 'ES'},
              {surname: 'Alba', position: 2, country: 'ES'},
              {surname: 'Torres', position: 3, country: 'ES'},
              {surname: 'Laporte', position: 4, country: 'ES'},
              {surname: 'Llorente', position: 5, country: 'ES'},
              {surname: 'Pedri', position: 6, country: 'ES'},
              {surname: 'Rodri', position: 7, country: 'ES'},
              {surname: 'Koke', position: 8, country: 'ES'},
              {surname: 'Olmo', position: 9, country: 'ES'},
              {surname: 'Morata', position: 10, country: 'ES'},
              {surname: 'Moreno', position: 11, country: 'ES'},
            ],
            substitutes: [
              {surname: 'Torres', position: 15, country: 'ES'},
              {surname: 'Sarabia', position: 16, country: 'ES'},
              {surname: 'Ruiz', position: 17, country: 'ES'},
              {surname: 'Oyarzabal', position: 18, country: 'ES'},
            ],
          },
          secondTeam: {
            formation: '1-3-5-2',
            footballers: [
              {surname: 'Szczęsny', position: 1, country: 'PL'},
              {surname: 'Glik', position: 2, country: 'PL'},
              {surname: 'Bednarek', position: 3, country: 'PL'},
              {surname: 'Bereszyński', position: 4, country: 'PL'},
              {surname: 'Puchacz', position: 5, country: 'PL'},
              {surname: 'Moder', position: 6, country: 'PL'},
              {surname: 'Zielinski', position: 7, country: 'PL'},
              {surname: 'Klich', position: 8, country: 'PL'},
              {surname: 'Jóźwiak', position: 9, country: 'PL'},
              {surname: 'Świderski', position: 10, country: 'PL'},
              {surname: 'Lewandowski', position: 11, country: 'PL'},
            ],
            substitutes: [
              {surname: 'Kozłowski', position: 15, country: 'PL'}, // Został najmłodszym graczem w historii Euro (w tamtym momencie)
              {surname: 'Frankowski', position: 16, country: 'PL'},
              {surname: 'Linetty', position: 17, country: 'PL'},
              {surname: 'Dawidowicz', position: 18, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 33,
    question: 'Włochy 1-1 (k. 3-2) Anglia (11.07.2021) Finał Mistrzostw Europy 2020',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Włochy - Anglia',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Donnarumma', position: 1, country: 'IT'},
              {surname: 'Emerson', position: 2, country: 'IT'},
              {surname: 'Chiellini', position: 3, country: 'IT'},
              {surname: 'Bonucci', position: 4, country: 'IT'},
              {surname: 'Di Lorenzo', position: 5, country: 'IT'},
              {surname: 'Verratti', position: 6, country: 'IT'},
              {surname: 'Jorginho', position: 7, country: 'IT'},
              {surname: 'Barella', position: 8, country: 'IT'},
              {surname: 'Insigne', position: 9, country: 'IT'},
              {surname: 'Immobile', position: 10, country: 'IT'},
              {surname: 'Chiesa', position: 11, country: 'IT'},
            ],
            substitutes: [
              {surname: 'Cristante', position: 15, country: 'IT'},
              {surname: 'Berardi', position: 16, country: 'IT'},
              {surname: 'Bernardeschi', position: 17, country: 'IT'},
              {surname: 'Locatelli', position: 18, country: 'IT'},
              {surname: 'Belotti', position: 19, country: 'IT'},
              {surname: 'Florenzi', position: 20, country: 'IT'},
            ],
          },
          secondTeam: {
            formation: '1-3-4-2-1',
            footballers: [
              {surname: 'Pickford', position: 1, country: 'ENG'},
              {surname: 'Stones', position: 2, country: 'ENG'},
              {surname: 'Maguire', position: 3, country: 'ENG'},
              {surname: 'Walker', position: 4, country: 'ENG'},
              {surname: 'Shaw', position: 5, country: 'ENG'}, // Strzelec gola w 2. minucie
              {surname: 'Rice', position: 6, country: 'ENG'},
              {surname: 'Phillips', position: 7, country: 'ENG'},
              {surname: 'Trippier', position: 8, country: 'ENG'},
              {surname: 'Sterling', position: 9, country: 'ENG'},
              {surname: 'Mount', position: 10, country: 'ENG'},
              {surname: 'Kane', position: 11, country: 'ENG'},
            ],
            substitutes: [
              {surname: 'Saka', position: 15, country: 'ENG'},
              {surname: 'Henderson', position: 16, country: 'ENG'},
              {surname: 'Grealish', position: 17, country: 'ENG'},
              {surname: 'Rashford', position: 18, country: 'ENG'},
              {surname: 'Sancho', position: 19, country: 'ENG'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 34,
    question: 'Hiszpania 2-1 Anglia (14.07.2024) Finał Mistrzostw Europy 2024',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Hiszpania - Anglia',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Simón', position: 1, country: 'ES'},
              {surname: 'Cucurella', position: 2, country: 'ES'},
              {surname: 'Laporte', position: 3, country: 'ES'},
              {surname: 'Le Normand', position: 4, country: 'ES'},
              {surname: 'Carvajal', position: 5, country: 'ES'},
              {surname: 'Ruiz', position: 6, country: 'ES'},
              {surname: 'Rodri', position: 7, country: 'ES'},
              {surname: 'Olmo', position: 8, country: 'ES'},
              {surname: 'Williams', position: 9, country: 'ES'},
              {surname: 'Morata', position: 10, country: 'ES'},
              {surname: 'Yamal', position: 11, country: 'ES'},
            ],
            substitutes: [
              {surname: 'Zubimendi', position: 15, country: 'ES'}, // wszedł za kontuzjowanego Rodriego w przerwie
              {surname: 'Oyarzabal', position: 16, country: 'ES'}, // strzelec zwycięskiej bramki
              {surname: 'Fernandez', position: 17, country: 'ES'},
              {surname: 'Merino', position: 18, country: 'ES'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Pickford', position: 1, country: 'ENG'},
              {surname: 'Shaw', position: 2, country: 'ENG'},
              {surname: 'Guéhi', position: 3, country: 'ENG'},
              {surname: 'Stones', position: 4, country: 'ENG'},
              {surname: 'Walker', position: 5, country: 'ENG'},
              {surname: 'Rice', position: 6, country: 'ENG'},
              {surname: 'Mainoo', position: 7, country: 'ENG'},
              {surname: 'Bellingham', position: 8, country: 'ENG'},
              {surname: 'Foden', position: 9, country: 'ENG'},
              {surname: 'Saka', position: 10, country: 'ENG'},
              {surname: 'Kane', position: 11, country: 'ENG'},
            ],
            substitutes: [
              {surname: 'Watkins', position: 15, country: 'ENG'},
              {surname: 'Palmer', position: 16, country: 'ENG'}, // strzelec bramki na 1-1
              {surname: 'Toney', position: 17, country: 'ENG'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 35,
    question: 'Borussia Dortmund 8-4 Legia Warszawa (22.11.2016) Faza grupowa Ligi Mistrzów 2016/2017',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Borussia Dortmund - Legia Warszawa',
        football: {
          firstTeam: {
            formation: '1-4-1-4-1',
            footballers: [
              {surname: 'Weidenfeller', position: 1, country: 'DE'},
              {surname: 'Passlack', position: 2, country: 'DE'},
              {surname: 'Bartra', position: 3, country: 'ES'},
              {surname: 'Ginter', position: 4, country: 'DE'},
              {surname: 'Rode', position: 5, country: 'DE'},
              {surname: 'Castro', position: 6, country: 'DE'},
              {surname: 'Sahin', position: 7, country: 'TR'},
              {surname: 'Dembélé', position: 8, country: 'FR'},
              {surname: 'Kagawa', position: 9, country: 'JP'},
              {surname: 'Pulisic', position: 10, country: 'US'},
              {surname: 'Reus', position: 11, country: 'DE'},
            ],
            substitutes: [
              {surname: 'Durm', position: 15, country: 'DE'},
              {surname: 'Schürrle', position: 16, country: 'DE'},
              {surname: 'Aubameyang', position: 17, country: 'GA'},
            ],
          },
          secondTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Cierzniak', position: 1, country: 'PL'},
              {surname: 'Rzeźniczak', position: 2, country: 'PL'},
              {surname: 'Pazdan', position: 3, country: 'PL'},
              {surname: 'Czerwiński', position: 4, country: 'PL'},
              {surname: 'Berenszyński', position: 5, country: 'PL'},
              {surname: 'Kopczyński', position: 6, country: 'PL'},
              {surname: 'Guilherme', position: 7, country: 'BR'},
              {surname: 'Radović', position: 8, country: 'RS'},
              {surname: 'Odjidja-Ofoe', position: 9, country: 'BE'},
              {surname: 'Kucharczyk', position: 10, country: 'PL'},
              {surname: 'Prijović', position: 11, country: 'CH'},
            ],
            substitutes: [
              {surname: 'Wieteska', position: 15, country: 'PL'},
              {surname: 'Nikolić', position: 16, country: 'HU'},
              {surname: 'Jodłowiec', position: 17, country: 'PL'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 36,
    question: 'Manchester City 2-3 Liverpool FC (16.04.2022) Półfinał Pucharu Anglii (FA Cup) 2021/2022',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Manchester City - Liverpool FC',
        football: {
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Steffen', position: 1, country: 'US'},
              {surname: 'Zinchenko', position: 2, country: 'UA'},
              {surname: 'Aké', position: 3, country: 'NL'},
              {surname: 'Stones', position: 4, country: 'ENG'},
              {surname: 'Cancelo', position: 5, country: 'PT'},
              {surname: 'Bernardo Silva', position: 6, country: 'PT'},
              {surname: 'Fernandinho', position: 7, country: 'BR'},
              {surname: 'Foden', position: 8, country: 'ENG'},
              {surname: 'Grealish', position: 9, country: 'ENG'},
              {surname: 'Gabriel Jesus', position: 10, country: 'BR'},
              {surname: 'Sterling', position: 11, country: 'ENG'},
            ],
            substitutes: [
              {surname: 'Mahrez', position: 15, country: 'DZ'},
            ],
          },
          secondTeam: {
            formation: '1-3-4-2-1',
            footballers: [
              {surname: 'Alisson', position: 1, country: 'BR'},
              {surname: 'Robertson', position: 2, country: 'GB-SCT'},
              {surname: 'van Dijk', position: 3, country: 'NL'},
              {surname: 'Konaté', position: 4, country: 'FR'},
              {surname: 'Alexander-Arnold', position: 5, country: 'ENG'},
              {surname: 'Alcantara', position: 6, country: 'ES'},
              {surname: 'Fabinho', position: 7, country: 'BR'},
              {surname: 'Keita', position: 8, country: 'GN'},
              {surname: 'Díaz', position: 9, country: 'CO'},
              {surname: 'Mané', position: 10, country: 'SN'},
              {surname: 'Salah', position: 11, country: 'EG'},
            ],
            substitutes: [
              {surname: 'Henderson', position: 15, country: 'ENG'},
              {surname: 'Jota', position: 16, country: 'PT'},
              {surname: 'Firmino', position: 17, country: 'BR'},
              {surname: 'Jones', position: 18, country: 'ENG'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 37,
    question: 'Real Madryt 2-6 FC Barcelona (02.05.2009) La Liga 2008/2009',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Real Madryt - FC Barcelona',
        football: {
          firstTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Casillas', position: 1, country: 'ES'},
              {surname: 'Heinze', position: 2, country: 'AR'},
              {surname: 'Cannavaro', position: 3, country: 'IT'},
              {surname: 'Metzelder', position: 4, country: 'DE'},
              {surname: 'Ramos', position: 5, country: 'ES'},
              {surname: 'Marcelo', position: 6, country: 'BR'},
              {surname: 'Lass Diarra', position: 7, country: 'FR'},
              {surname: 'Gago', position: 8, country: 'AR'},
              {surname: 'Robben', position: 9, country: 'NL'},
              {surname: 'Higuaín', position: 10, country: 'AR'},
              {surname: 'Raúl', position: 11, country: 'ES'},
            ],
            substitutes: [
              {surname: 'Huntelaar', position: 15, country: 'NL'},
              {surname: 'Van der Vaart', position: 16, country: 'NL'},
              {surname: 'García', position: 17, country: 'ES'},
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Valdés', position: 1, country: 'ES'},
              {surname: 'Abidal', position: 2, country: 'FR'},
              {surname: 'Piqué', position: 3, country: 'ES'},
              {surname: 'Puyol', position: 4, country: 'ES'},
              {surname: 'Dani Alves', position: 5, country: 'BR'},
              {surname: 'Toure', position: 6, country: 'CI'},
              {surname: 'Xavi', position: 7, country: 'ES'},
              {surname: 'Iniesta', position: 8, country: 'ES'},
              {surname: 'Henry', position: 9, country: 'FR'},
              {surname: 'Messi', position: 10, country: 'AR'},
              {surname: 'Etto', position: 11, country: 'CM'},
            ],
            substitutes: [
              {surname: 'Keita', position: 15, country: 'ML'},
              {surname: 'Busquets', position: 16, country: 'ES'},
              {surname: 'Bojan', position: 17, country: 'ES'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 38,
    question: 'Lech Poznań 3-1 Manchester City (04.11.2010) Faza grupowa Ligi Europy 2010/2011',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Lech Poznań - Manchester City',
        football: {
          firstTeam: {
            formation: '1-4-2-3-1',
            footballers: [
              {surname: 'Buric', position: 1, country: 'BIH'},
              {surname: 'Henríquez', position: 2, country: 'PA'},
              {surname: 'Arboleda', position: 3, country: 'CO'},
              {surname: 'Bosacki', position: 4, country: 'PL'},
              {surname: 'Kikut', position: 5, country: 'PL'},
              {surname: 'Injac', position: 6, country: 'RS'},
              {surname: 'Djurdjevic', position: 7, country: 'RS'},
              {surname: 'Krivets', position: 8, country: 'BY'},
              {surname: 'Peszko', position: 9, country: 'PL'},
              {surname: 'Rudnevs', position: 10, country: 'LV'},
              {surname: 'Stilić', position: 11, country: 'CD'},
            ],
            substitutes: [
              {surname: 'Kiełb', position: 15, country: 'PL'},
              {surname: 'Możdżeń', position: 16, country: 'PL'}, // Strzelec bramki-stadiony świata na 3-1
              {surname: 'Wilk', position: 17, country: 'PL'},
            ],
          },
          secondTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Given', position: 1, country: 'IE'},
              {surname: 'Lescott', position: 2, country: 'ENG'},
              {surname: 'Boyata', position: 3, country: 'BE'},
              {surname: 'Richards', position: 4, country: 'ENG'},
              {surname: 'Zabaleta', position: 5, country: 'AR'},
              {surname: 'Vieira', position: 6, country: 'FR'},
              {surname: 'Bridge', position: 7, country: 'ENG'},
              {surname: 'Milner', position: 8, country: 'ENG'},
              {surname: 'Johnson', position: 9, country: 'GB_ENG'},
              {surname: 'Adebayor', position: 10, country: 'TG'},
              {surname: 'Wright-Phillips', position: 11, country: 'ENG'},
            ],
            substitutes: [
              {surname: 'Kompany', position: 15, country: 'BE'},
              {surname: 'Kolarov', position: 16, country: 'RS'},
              {surname: 'Silva', position: 17, country: 'ES'},
            ],
          },
        },
      },
    ],
  },
  {
    id: 39,
    question: 'Piast Gliwice 0-1 Górnik Zabrze (26.07.2025) Ekstraklasa 2025/2026',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'Piast Gliwice - Górnik Zabrze',
        football: {
          firstTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'Plach', position: 1, country: 'SK'},
              {surname: 'Drapiński', position: 2, country: 'PL'},
              {surname: 'Czerwiński', position: 3, country: 'PL'},
              {surname: 'Twumasi', position: 4, country: 'GH'},
              {surname: 'Tomasiewicz', position: 5, country: 'PL'},
              {surname: 'Boisgard', position: 6, country: 'FR'},
              {surname: 'Dziczek', position: 7, country: 'PL'},
              {surname: 'Felix', position: 8, country: 'ES'},
              {surname: 'Jirka', position: 9, country: 'SK'},
              {surname: 'Chrapek', position: 10, country: 'PL'},
              {surname: 'Barkowsky', position: 11, country: 'BY'}
            ],
            substitutes: [
              {surname: 'Sanca', position: 15, country: 'GW'},
              {surname: 'Mucha', position: 16, country: 'PL'},
              {surname: 'Lewicki', position: 17, country: 'PL'}
            ],
          },
          secondTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Lubik', position: 1, country: 'PL'},
              {surname: 'Janža', position: 2, country: 'SI'},
              {surname: 'Josema', position: 3, country: 'ES'},
              {surname: 'Janicki', position: 4, country: 'PL'},
              {surname: 'Olkowski', position: 5, country: 'PL'},
              {surname: 'Kubicki', position: 6, country: 'NG'},
              {surname: 'Podolski', position: 7, country: 'DE'},
              {surname: 'Hellebrand', position: 8, country: 'CZ'},
              {surname: 'Lukoszek', position: 9, country: 'PL'},
              {surname: 'Ismaheel', position: 10, country: 'NG'},
              {surname: 'Tsirigotis', position: 11, country: 'GR'}
            ],
            substitutes: [
              {surname: 'Massimo', position: 15, country: 'DE'},
              {surname: 'Dziegielewski', position: 16, country: 'PL'},
              {surname: 'jun Goh', position: 17, country: 'KR'},
              {surname: 'Szcześniak', position: 18, country: 'PL'}
            ]
          }
        }
      }
    ]
  },
  {
    id: 40,
    question: 'FC Barcelona 2-0 Manchester United (27.05.2009) Finał Ligi Mistrzów 2008/2009',
    hints: [],
    revealedAnswers: [],
    showAnswer: false,
    answers: [
      {
        value: 'FC Barcelona - Manchester United',
        football: {
          firstTeam: {
            formation: '1-4-3-3',
            footballers: [
              {surname: 'Valdes', position: 1, country: 'ES'},
              {surname: 'Sylvinho', position: 2, country: 'BR'},
              {surname: 'Piqué', position: 3, country: 'ES'},
              {surname: 'Toure', position: 4, country: 'CI'},
              {surname: 'Puyol', position: 5, country: 'ES'},
              {surname: 'Busquets', position: 6, country: 'ES'},
              {surname: 'Xavi', position: 7, country: 'ES'},
              {surname: 'Iniesta', position: 8, country: 'ES'},
              {surname: 'Henry', position: 9, country: 'FR'},
              {surname: 'Etto', position: 10, country: 'CM'},
              {surname: 'Messi', position: 11, country: 'AR'},
            ],
            substitutes: [
              {surname: 'Keita', position: 15, country: 'ML'},
              {surname: 'Pedro', position: 16, country: 'ES'}
            ],
          },
          secondTeam: {
            formation: '1-4-4-2',
            footballers: [
              {surname: 'van der Sar', position: 1, country: 'NL'},
              {surname: 'Evra', position: 2, country: 'FR'},
              {surname: 'Vidić', position: 3, country: 'RS'},
              {surname: 'Ferdinand', position: 4, country: 'ENG'},
              {surname: 'OShea', position: 5, country: 'IE'},
              {surname: 'Carrick', position: 6, country: 'ENG'},
              {surname: 'Giggs', position: 7, country: 'GB-WLS'},
              {surname: 'Anderson', position: 8, country: 'BR'},
              {surname: 'Rooney', position: 9, country: 'ENG'},
              {surname: 'Ronaldo', position: 10, country: 'PT'},
              {surname: 'Park', position: 11, country: 'KR'},
            ],
            substitutes: [
              {surname: 'Tevez', position: 15, country: 'AR'},
              {surname: 'Berbatov', position: 16, country: 'BG'},
              {surname: 'Scholes', position: 17, country: 'ENG'},
            ],
          },
        },
      },
    ],
  }
];
