export const MIASTO_WOJEWODZTWO = [
  {
    id: 1,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Warszawa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 2,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Kraków?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 3,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Łódź?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 4,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Wrocław?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 5,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Poznań?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 6,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Gdańsk?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 7,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Szczecin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 8,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Bydgoszcz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 9,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Lublin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 10,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Białystok?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 11,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Katowice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 12,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Gdynia?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 13,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Częstochowa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 14,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Radom?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 15,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Toruń?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 16,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Sosnowiec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 17,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Kielce?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 18,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Rzeszów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 19,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Gliwice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 20,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Zabrze?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 21,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Olsztyn?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 22,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Bielsko-Biała?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 23,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Bytom?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 24,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Rybnik?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 25,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Ruda Śląska?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 26,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Zielona Góra?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 27,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Tychy?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 28,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Opole?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 29,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Gorzów Wielkopolski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 30,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Dąbrowa Górnicza?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 31,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Płock?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 32,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Elbląg?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 33,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Wałbrzych?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 34,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Chorzów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 35,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Tarnów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 36,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Koszalin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 37,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Kalisz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 38,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Legnica?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 39,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Włocławek?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 40,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Grudziądz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 41,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Jaworzno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 42,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Jelenia Góra?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 43,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Siedlce?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 44,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Mysłowice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 45,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Piotrków Trybunalski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 46,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Konin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 47,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Inowrocław?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 48,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Ostrowiec Świętokrzyski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 49,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Suwałki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 50,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Gniezno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 51,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Przemyśl?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 52,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Głogów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 53,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Zamość?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 54,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Pabianice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 55,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Leszno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 56,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Łomża?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 57,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Ełk?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 58,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Tarnowskie Góry?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 59,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Chełm?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 60,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Pruszków?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 61,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Mielec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 62,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Bełchatów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 63,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Świdnica?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 64,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Biała Podlaska?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 65,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Będzin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 66,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Legionowo?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 67,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Ostrołęka?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 68,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Puławy?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 69,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Starogard Gdański?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 70,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Skierniewice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 71,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Tarnobrzeg?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 72,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Starachowice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 73,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Kutno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 74,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Rumia?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 75,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Nysa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 76,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Kołobrzeg?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 77,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Dębica?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 78,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Ciechanów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 79,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Świdnik?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 80,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Otwock?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 81,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Sieradz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 82,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Mikołów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 83,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Świnoujście?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 84,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Kwidzyn?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 85,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Chojnice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 86,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Nowa Sól?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 87,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Bolesławiec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 88,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Oświęcim?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 89,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Malbork?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 90,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Żary?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 91,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Jarosław?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 92,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Sopot?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 93,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Chrzanów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 94,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Brzeg?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 95,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Jasło?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 96,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Lębork?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 97,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Cieszyn?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 98,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Czeladź?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 99,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Kraśnik?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 100,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Nowy Targ?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 101,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Iława?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 102,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Police?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 103,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Dzierżoniów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 104,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Grodzisk Mazowiecki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 105,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Zgorzelec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 106,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Łowicz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 107,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Łuków?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 108,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Bielsk Podlaski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 109,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Bielawa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 110,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Augustów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 111,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Bochnia?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 112,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Mława?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 113,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Giżycko?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 114,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Brodnica?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 115,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Krotoszyn?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 116,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Kętrzyn?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 117,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Zakopane?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 118,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Gorlice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 119,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Biłgoraj?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 120,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Kłodzko?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 121,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Luboń?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 122,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Brzozów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 123,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Wałcz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 124,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Kluczbork?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 125,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Jarocin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 126,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Świecie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 127,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Wągrowiec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 128,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Skawina?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 129,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Sandomierz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 130,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Białogard?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 131,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Kościan?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 132,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Kościerzyna?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 133,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Szczytno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 134,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Ostrów Mazowiecka?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 135,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Jawor?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 136,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Goleniów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 137,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Lubartów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 138,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Świedbodzin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 139,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Grajewo?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 140,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Wieliczka?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 141,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Łęczna?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 142,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Opoczno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 143,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Koło?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 144,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Działdowo?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 145,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Prudnik?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 146,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Gryfino?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 147,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Hajnówka?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 148,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Chełmno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 149,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Pleszew?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 150,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Gostyń?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 151,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Nakło nad Notecią?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 152,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Pułtusk?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 153,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Chodzież?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 154,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Krasnystaw?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 155,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Gostynin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 156,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Międzyrzecz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 157,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Łask?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 158,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Oborniki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 159,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Rawa Mazowiecka?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 160,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Łańcut?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 161,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Garwolin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 162,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Kozienice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 163,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Braniewo?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 164,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Bytów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 165,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Brzesko?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 166,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Grójec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 167,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Krapkowice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 168,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Rypin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 169,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Gryfice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 170,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Olecko?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 171,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Złotoryja?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 172,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Przeworsk?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 173,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Łęczyca?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 174,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Jędrzejów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 175,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Siemiatycze?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 176,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Choszczno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 177,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Limanowa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 178,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Grodzisk Wielkopolski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 179,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Wschowa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 180,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Nidzica?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 181,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Człuchów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 182,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Gołdap?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 183,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Głubczyce?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 184,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Wolsztyn?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 185,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Trzebnica?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 186,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Włodawa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 187,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Golub-Dobrzyń?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 188,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Brzeziny?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 189,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Lubaczów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 190,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Aleksandrów Kujawski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 191,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Węgorzewo?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 192,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Janów Lubelski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 193,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Góra?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 194,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Drawsko Pomorskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 195,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Krosno Odrzańskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 196,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Nowe description Lubawskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 197,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Kolno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 198,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Lwówek Śląski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 199,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Kamień Pomorski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 200,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Kolbuszowa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 201,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Kazimierza Wielka?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 202,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Hrubieszów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 203,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Świętochłowice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 204,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Lubin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 205,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Mińsk Mazowiecki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 206,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Żyrardów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 207,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Tczew?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 208,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Ostróda?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 209,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Siemianowice Śląskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 210,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Puck?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 211,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Wejherowo?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 212,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Sokołów Podlaski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 213,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Płońsk?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 214,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Wąbrzeźno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 215,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Mrągowo?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 216,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Pruszcz Gdański?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 217,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Zduńska Wola?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 218,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Oleśnica?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 219,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Ostrów Wielkopolski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 220,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Turek?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 221,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Złotów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 222,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Tomaszów Mazowiecki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 223,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Tomaszów Lubelski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 224,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Nowy Sącz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 225,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Sochaczew?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 226,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Piekary Śląskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 227,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Stargard Szczeciński?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 228,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Lipno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 229,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Zgierz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 230,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Lubań?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 231,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Nowy Dwór Mazowiecki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 232,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Zambrów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 233,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Szczecinek?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 234,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Sejny?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 235,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Oława?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 236,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Czarnków?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 237,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Lidzbark Warmiński?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 238,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Kamienna Góra?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 239,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Słupca?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 240,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Jastrzębie-Zdrój?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 241,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Krosno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 242,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Skarżysko-Kamienna?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 243,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Sanok?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 244,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Radziejów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 245,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Bartoszyce?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 246,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Maków Mazowiecki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 247,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Sierpc?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 248,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Wodzisław Śląski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 249,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Żory?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 250,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Radomsko?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 251,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Wołomin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 252,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Radzyń Podlaski?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 253,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Sławno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 254,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Stalowa Wola?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 255,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Racibórz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 256,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Piła?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 257,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Żywiec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 258,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Świdwin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 259,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Przasnysz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 260,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Żagań?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 261,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Piaseczno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 262,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Wysokie Mazowieckie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 263,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Leżajsk?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 264,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Zawiercie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 265,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Kędzierzyn-Koźle?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 266,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Bieruń?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 267,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Myszków?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 268,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Słupsk?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 269,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Węgrów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 270,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Wadowice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 271,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Olkusz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 272,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Sucha Beskidzka?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 273,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Ożarów Mazowiecki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 274,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Pszczyna?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 275,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Myślenice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 276,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Lubliniec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 277,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Wieluń?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 278,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Wyszków?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 279,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Rawicz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 280,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Września?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 281,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Śrem?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 282,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Kępno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 283,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Ropczyce?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 284,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Dąbrowa Tarnowska?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 285,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Polkowice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 286,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Kartuzy?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 287,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Szamotuły?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 288,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Proszowice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 289,
    answers: [{ value: 'Śląskie' }],
    question: ' Z jakiego województwa jest: Kłobuck?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 290,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Nisko?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 291,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Ząbkowice Śląskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 292,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Strzelce Opolskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 293,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Strzyżów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 294,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Środa Wielkopolska?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 295,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Wieruszów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 296,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Końskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 297,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Busko-Zdrój?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 298,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Nowy Tomyśl?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 299,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Białobrzegi?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 300,
    answers: [{ value: 'Małopolskie' }],
    question: ' Z jakiego województwa jest: Miechów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 301,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Ryki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 302,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Ostrzeszów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 303,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Strzelin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 304,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Szydłowiec?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 305,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Staszów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 306,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Żuromin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 307,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Opatów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 308,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Sztum?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 309,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Słubice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 310,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Lesko?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 311,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Żnin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 312,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Pajęczno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 313,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Parczew?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 314,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Mogilno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 315,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Pińczów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 316,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Pyrzyce?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 317,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Mońki?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 318,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Środa Śląska?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 319,
    answers: [{ value: 'Lubelskie' }],
    question: ' Z jakiego województwa jest: Opole Lubelskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 320,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Łosice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 321,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Zwoleń?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 322,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Namysłów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 323,
    answers: [{ value: 'Pomorskie' }],
    question: ' Z jakiego województwa jest: Nowy Dwór Gdański?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 324,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Tuchola?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 325,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Lipsko?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 326,
    answers: [{ value: 'Podlaskie' }],
    question: ' Z jakiego województwa jest: Sokółka?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 327,
    answers: [{ value: 'Świętokrzyskie' }],
    question: ' Z jakiego województwa jest: Włoszczowa?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 328,
    answers: [{ value: 'Opolskie' }],
    question: ' Z jakiego województwa jest: Olesno?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 329,
    answers: [{ value: 'Kujawsko-Pomorskie' }],
    question: ' Z jakiego województwa jest: Sępólno Krajeńskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 330,
    answers: [{ value: 'Łódzkie' }],
    question: ' Z jakiego województwa jest: Poddębice?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 331,
    answers: [{ value: 'Mazowieckie' }],
    question: ' Z jakiego województwa jest: Przysucha?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 332,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Wołów?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 333,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Myślibórz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 334,
    answers: [{ value: 'Zachodniopomorskie' }],
    question: ' Z jakiego województwa jest: Łobez?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 335,
    answers: [{ value: 'Dolnośląskie' }],
    question: ' Z jakiego województwa jest: Milicz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 336,
    answers: [{ value: '' }],
    question: ' Z jakiego województwa jest: Strzelce Krajeńskie?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 337,
    answers: [{ value: 'Warmińsko-Mazurskie' }],
    question: ' Z jakiego województwa jest: Pisz?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 338,
    answers: [{ value: 'Lubuskie' }],
    question: ' Z jakiego województwa jest: Sulęcin?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 339,
    answers: [{ value: 'Podkarpackie' }],
    question: ' Z jakiego województwa jest: Ustrzyki Dolne?',
    hints: [],
    revealedAnswers: [],
  },
  {
    id: 340,
    answers: [{ value: 'Wielkopolskie' }],
    question: ' Z jakiego województwa jest: Międzychód?',
    hints: [],
    revealedAnswers: [],
  },
];
